// SPDX-License-Identifier: Apache-2.0
// Version 1 wire contract for an outbound data-plane connector.
//
// Connector authentication is carried exclusively in the transport
// Authorization header. No connector credential belongs in a message body.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/connectorproto/connector.proto

package connectorprotoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	connectorproto "github.com/agentarea/mcp-manager/internal/connectorproto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OutboundConnectorName is the fully-qualified name of the OutboundConnector service.
	OutboundConnectorName = "agentarea.connector.v1.OutboundConnector"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OutboundConnectorConnectProcedure is the fully-qualified name of the OutboundConnector's Connect
	// RPC.
	OutboundConnectorConnectProcedure = "/agentarea.connector.v1.OutboundConnector/Connect"
)

// OutboundConnectorClient is a client for the agentarea.connector.v1.OutboundConnector service.
type OutboundConnectorClient interface {
	Connect(context.Context) *connect.BidiStreamForClient[connectorproto.ConnectorToControl, connectorproto.ControlToConnector]
}

// NewOutboundConnectorClient constructs a client for the agentarea.connector.v1.OutboundConnector
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOutboundConnectorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OutboundConnectorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	outboundConnectorMethods := connectorproto.File_internal_connectorproto_connector_proto.Services().ByName("OutboundConnector").Methods()
	return &outboundConnectorClient{
		connect: connect.NewClient[connectorproto.ConnectorToControl, connectorproto.ControlToConnector](
			httpClient,
			baseURL+OutboundConnectorConnectProcedure,
			connect.WithSchema(outboundConnectorMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
	}
}

// outboundConnectorClient implements OutboundConnectorClient.
type outboundConnectorClient struct {
	connect *connect.Client[connectorproto.ConnectorToControl, connectorproto.ControlToConnector]
}

// Connect calls agentarea.connector.v1.OutboundConnector.Connect.
func (c *outboundConnectorClient) Connect(ctx context.Context) *connect.BidiStreamForClient[connectorproto.ConnectorToControl, connectorproto.ControlToConnector] {
	return c.connect.CallBidiStream(ctx)
}

// OutboundConnectorHandler is an implementation of the agentarea.connector.v1.OutboundConnector
// service.
type OutboundConnectorHandler interface {
	Connect(context.Context, *connect.BidiStream[connectorproto.ConnectorToControl, connectorproto.ControlToConnector]) error
}

// NewOutboundConnectorHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOutboundConnectorHandler(svc OutboundConnectorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	outboundConnectorMethods := connectorproto.File_internal_connectorproto_connector_proto.Services().ByName("OutboundConnector").Methods()
	outboundConnectorConnectHandler := connect.NewBidiStreamHandler(
		OutboundConnectorConnectProcedure,
		svc.Connect,
		connect.WithSchema(outboundConnectorMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentarea.connector.v1.OutboundConnector/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OutboundConnectorConnectProcedure:
			outboundConnectorConnectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOutboundConnectorHandler returns CodeUnimplemented from all methods.
type UnimplementedOutboundConnectorHandler struct{}

func (UnimplementedOutboundConnectorHandler) Connect(context.Context, *connect.BidiStream[connectorproto.ConnectorToControl, connectorproto.ControlToConnector]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentarea.connector.v1.OutboundConnector.Connect is not implemented"))
}
