# Ory Kratos Configuration for AgentArea

version: v1.1.0

# DSN is overridden via docker-compose environment variable
# Default for reference: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/kratos
dsn: postgres://postgres:postgres@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:3001
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3000/workplace
    - http://localhost:3000/dashboard

  flows:
    error:
      ui_url: http://localhost:3000/auth/error

    settings:
      ui_url: http://localhost:3000/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
      use: code
      after:
        default_browser_return_url: http://localhost:3000/workplace

    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login

    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m
      after:
        default_browser_return_url: http://localhost:3000/workplace

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/auth/registration
      after:
        default_browser_return_url: http://localhost:3000/workplace

  methods:
    password:
      enabled: true
    code:
      enabled: true

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE-dev-only
  cipher:
    - SECRET-KEY-FOR-DEV-32-CHARACTERS

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://user:pass@mailslurper:1025/?skip_ssl_verify=true
    from_address: noreply@example.com
    from_name: AgentArea

session:
  cookie:
    same_site: Lax
    domain: localhost
    path: /
  whoami:
    tokenizer:
      templates:
        agentarea_jwt:
          jwks_url: base64://ewogICJrZXlzIjogWwogICAgewogICAgICAia3R5IjogIkVDIiwKICAgICAgImtpZCI6ICJhZ2VudGFyZWEtand0LWtleS0xIiwKICAgICAgInVzZSI6ICJzaWciLAogICAgICAiYWxnIjogIkVTMjU2IiwKICAgICAgImNydiI6ICJQLTI1NiIsCiAgICAgICJ4IjogIk1LQkNUTkljS1VTRGlpMTF5U3MzNTI2aURaOEFpVG83VHU2S1BBcXY3RDQiLAogICAgICAieSI6ICI0RXRsNlNSVzJZaUxVck41dmZ2Vkh1aHA3eDhQeGx0bVdXbGJiTTRJRnlNIiwKICAgICAgImQiOiAiODcwTUI2Z2Z1VEo0SHRVblV2WU15SnByNWVVWk5QNEJrNDNiVmRqM2VBRSIKICAgIH0KICBdCn0=
          claims_mapper_url: base64://bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcignY2xhaW1zJyk7CmxvY2FsIHNlc3Npb24gPSBzdGQuZXh0VmFyKCdzZXNzaW9uJyk7CmxvY2FsIGlkZW50aXR5ID0gc3RkLmV4dFZhcignaWRlbnRpdHknKTsKCnsKICAvLyBTdGFuZGFyZCBKV1QgY2xhaW1zCiAgaXNzOiAnaHR0cHM6Ly9hZ2VudGFyZWEuZGV2JywKICBzdWI6IGlkZW50aXR5LmlkLAogIGF1ZDogJ2FnZW50YXJlYS1hcGknLAogIGV4cDogc3RkLnBhcnNlSW50KHN0ZC5zcGxpdChzZXNzaW9uLmV4cGlyZXNfYXQsICcuJylbMF0pLAogIGlhdDogc3RkLnBhcnNlSW50KHN0ZC5zcGxpdChzZXNzaW9uLmlzc3VlZF9hdCwgJy4nKVswXSksCgogIC8vIEN1c3RvbSBjbGFpbXMKICBlbWFpbDogaWYgc3RkLm9iamVjdEhhcyhpZGVudGl0eS50cmFpdHMsICdlbWFpbCcpIHRoZW4gaWRlbnRpdHkudHJhaXRzLmVtYWlsIGVsc2UgbnVsbCwKICB1c2VybmFtZTogaWYgc3RkLm9iamVjdEhhcyhpZGVudGl0eS50cmFpdHMsICd1c2VybmFtZScpIHRoZW4gaWRlbnRpdHkudHJhaXRzLnVzZXJuYW1lIGVsc2UgbnVsbCwKICBuYW1lOiBpZiBzdGQub2JqZWN0SGFzKGlkZW50aXR5LnRyYWl0cywgJ25hbWUnKSB0aGVuIHsKICAgIGZpcnN0OiBpZiBzdGQub2JqZWN0SGFzKGlkZW50aXR5LnRyYWl0cy5uYW1lLCAnZmlyc3QnKSB0aGVuIGlkZW50aXR5LnRyYWl0cy5uYW1lLmZpcnN0IGVsc2UgbnVsbCwKICAgIGxhc3Q6IGlmIHN0ZC5vYmplY3RIYXMoaWRlbnRpdHkudHJhaXRzLm5hbWUsICdsYXN0JykgdGhlbiBpZGVudGl0eS50cmFpdHMubmFtZS5sYXN0IGVsc2UgbnVsbCwKICB9IGVsc2UgbnVsbCwKCiAgLy8gS3JhdG9zIHNwZWNpZmljIGNsYWltcwogIHNjaGVtYV9pZDogaWRlbnRpdHkuc2NoZW1hX2lkLAogIGFhbDogc2Vzc2lvbi5hdXRoZW50aWNhdG9yX2Fzc3VyYW5jZV9sZXZlbCwKICBzZXNzaW9uX2lkOiBzZXNzaW9uLmlkLAp9Cg==
          ttl: 30m