[sandbox_hosts]
sandbox-ru-1 ansible_host=72.56.235.217 ansible_user=root

[sandbox_hosts:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
ansible_python_interpreter=/usr/bin/python3
sandbox_region=ru-3-msk-1
