{{- if .Values.mcpManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentarea.fullname" . }}-mcp-manager
  labels:
    {{- include "agentarea.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-manager
spec:
  type: {{ .Values.mcpManager.service.type }}
  ports:
    - port: {{ .Values.mcpManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentarea.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-manager
{{- end }}
