# These are supported funding model platforms
# Uncomment and add your funding information as needed

# github: [username1, username2]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://example.com/sponsor']