"""Replay patch ids. Histories recorded before each change replay its old commands."""

GOVERNANCE_VERDICT_PATCH = "governance-verdict-to-hitl-v1"
THINKING_ONLY_REPLY_PATCH = "thinking-only-reply-is-empty-v1"
APPROVAL_RESPONSE_ONCE_PATCH = "approval-response-once-v1"
DELEGATION_ON_OWN_QUEUE_PATCH = "delegation-on-own-task-queue-v1"
MONTHLY_CAP_AT_START_PATCH = "monthly-cap-at-start"
INTERACTION_CONTRACT_PATCH = "channel-aware-interaction-v1"
LONG_RUN_LOOP_PATCH = "long-run-loop-checks-v1"
COMPACTION_BOUNDS_PAYLOAD_PATCH = "compaction-bounds-payload-v1"
CANCELLATION_PROPAGATES_PATCH = "cancellation-propagates-v1"
