version: "3.8"
services:
  app:
    container_name: agentarea-backend
    build:
      context: core
    ports:
      - "8000:8000"
    restart: always
    environment:
      # S3 settings
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_REGION=${MINIO_REGION}
      - S3_BUCKET_NAME=${DOCUMENTS_BUCKET}
      - AWS_ENDPOINT_URL=http://minio:9000
      # Database settings
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # MCP settings
      - MCP_MANAGER_URL=http://mcp-manager:8000
      - REDIS_URL=redis://redis:6379
      - MCP_CLIENT_TIMEOUT=30
      # Server settings
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RELOAD=${RELOAD:-true}
      - WORKERS=${WORKERS:-1}
    volumes:
      - ./core/agentarea:/app/agentarea
      - ./core/alembic:/app/alembic
      - ${INFISICAL_TOKEN_VOLUME:-./.volumes/infisical-local-data}:/app/bootstrap
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_started
      app_migrations:
        condition: service_completed_successfully
      bootstrap:
        condition: service_completed_successfully
      mcp-manager:
        condition: service_healthy
    networks:
      - default
      - mcp-network
    command: ["python", "-m", "cli", "serve", "--reload", "--log-level=${LOG_LEVEL:-info}", "--workers=${WORKERS:-1}"]

  app_migrations:
    build:
      context: core
    environment:
    ## Have to add it for now
          # S3 settings
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_REGION=${MINIO_REGION}
      - S3_BUCKET_NAME=${DOCUMENTS_BUCKET}
      - AWS_ENDPOINT_URL=http://minio:9000
      # Only database settings
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./core/alembic:/app/alembic
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-m", "cli", "migrate"]

  bootstrap:
    build:
      context: bootstrap
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/llm
      - ${INFISICAL_TOKEN_VOLUME:-./.volumes/infisical-local-data}/bootstrap/data:/app/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=http://minio:9000
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-your-secure-password}
      - ORGANIZATION_NAME=${ORGANIZATION_NAME:-your-org-name}
      - INFISICAL_URL=http://infisical:8080
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LLM_PROVIDERS_YAML=/app/llm/providers.yaml
      - MCP_PROVIDERS_YAML=/app/llm/mcp_providers.yaml
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      app_migrations:
        condition: service_completed_successfully
      infisical:
        condition: service_started

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  infisical:
    container_name: infisical-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    image: infisical/infisical:latest-postgres
    env_file: .env
    ports:
      - 3333:8080
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/infisical
  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - default
      - mcp-network
    command: ["redis-server", "--save", "", "--appendonly", "no"]  # Disable persistence for dev

  # MCP Infrastructure Services
  mcp-manager:
    build:
      context: mcp-infrastructure/go-mcp-manager
      dockerfile: Dockerfile.dev
      target: development
    container_name: mcp-manager
    restart: unless-stopped
    privileged: true
    ports:
      - "7999:8000"  # MCP Manager API
      - "81:80"      # Traefik HTTP (different port to avoid conflict with main app)
      - "8443:443"   # Traefik HTTPS (different port to avoid conflict)
      - "8081:8080"  # Traefik dashboard
    expose:
      - "8000"
      - "80"
      - "443"
      - "8080"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - mcp_containers:/var/lib/containers/storage
      - ./mcp-infrastructure/docker/templates:/app/templates:ro
      - ./mcp-infrastructure/go-mcp-manager:/app:rw  # Mount source code for live reload
      - ./mcp-infrastructure/traefik:/etc/traefik:rw  # Traefik configuration
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${INFISICAL_TOKEN_VOLUME:-./.volumes/infisical-local-data}/bootstrap/data:/app/bootstrap/data:ro  # Access to Infisical bootstrap token
    networks:
      - mcp-network
    environment:
      - LOG_LEVEL=INFO
      - TRAEFIK_NETWORK=podman
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data:
  minio_data: 
  redis_data:
  infisical_bootstrap:
  mcp_containers:
    driver: local

networks:
  infisical:
    driver: bridge
  mcp-network:
    driver: bridge

