version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: catalogue/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      RUN_MIGRATIONS: "true"
      PORT: "8000"

volumes:
  db-data:
