"""A generic webhook is signed from the moment it is created, and can be re-signed.

The secret is generated by the API and shown exactly once. What matters is that
the value handed to the person is the one the webhook endpoint then checks
requests against, so these tests verify signatures with the endpoint's own
verifier over the secret store the API wrote.
"""

import hashlib
import hmac
from datetime import UTC, datetime
from types import SimpleNamespace
from unittest.mock import AsyncMock
from uuid import uuid4

import pytest
from agentarea_api.api.deps.services import (
    get_audit_service,
    get_secret_catalog_service,
    get_secret_manager,
    get_trigger_service,
)
from agentarea_api.api.v1 import triggers
from agentarea_common.auth.context import UserContext
from agentarea_common.auth.dependencies import get_user_context
from agentarea_common.infrastructure.secret_manager import BaseSecretManager
from agentarea_common.testing import allow_all_permissions, install_graph_ownership_stub
from agentarea_secrets.catalog_service import SecretCatalogService
from agentarea_triggers.webhook_verification import verify_webhook_signature
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient

BODY = b'{"event":"order.created"}'


@pytest.fixture(autouse=True)
def _graph_ownership(monkeypatch):
    allow_all_permissions()
    return install_graph_ownership_stub(monkeypatch)


class _MemorySecrets(BaseSecretManager):
    def __init__(self):
        self.values: dict[str, str] = {}

    async def get_secret(self, secret_name: str) -> str | None:
        return self.values.get(secret_name)

    async def set_secret(self, secret_name: str, secret_value: str) -> None:
        self.values[secret_name] = secret_value

    async def delete_secret(self, secret_name: str) -> bool:
        return self.values.pop(secret_name, None) is not None

    async def has_secret(self, secret_name: str) -> bool:
        return secret_name in self.values

    def external_ref(self, secret_name: str) -> str | None:
        return None


def _trigger(webhook_type: str, validation_rules: dict | None = None):
    now = datetime.now(UTC)
    return SimpleNamespace(
        id=uuid4(),
        name="Inbound",
        description="",
        agent_id=uuid4(),
        trigger_type="webhook",
        is_active=True,
        task_parameters={},
        conditions={},
        created_at=now,
        updated_at=now,
        created_by="user-a",
        failure_threshold=5,
        consecutive_failures=0,
        last_execution_at=None,
        webhook_id="inbound-hook-0123456789",
        webhook_type=webhook_type,
        allowed_methods=["POST"],
        validation_rules=validation_rules or {},
        webhook_config={},
        event_types=[],
    )


def _app(trigger, secrets: _MemorySecrets):
    service = AsyncMock()
    service.create_trigger.return_value = trigger
    service.get_trigger.return_value = trigger
    app = FastAPI()
    app.include_router(triggers.router, prefix="/v1/workspaces/{workspace}")
    app.dependency_overrides[get_user_context] = lambda: UserContext(
        user_id="user-a", workspace_id="workspace-a"
    )
    app.dependency_overrides[get_trigger_service] = lambda: service
    app.dependency_overrides[get_secret_manager] = lambda: secrets
    app.dependency_overrides[get_secret_catalog_service] = lambda: AsyncMock(
        spec=SecretCatalogService
    )
    app.dependency_overrides[triggers.get_channel_webhook_service] = lambda: AsyncMock()
    app.dependency_overrides[get_audit_service] = lambda: AsyncMock()
    return app


async def _post(app, path, json=None):
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        return await client.post(f"/v1/workspaces/acme/triggers{path}", json=json)


async def _accepted(trigger, secrets, headers) -> bool | None:
    return await verify_webhook_signature(
        trigger.webhook_type,
        trigger.validation_rules,
        trigger.webhook_config,
        headers,
        BODY,
        secret_reader=secrets,
        trigger_id=trigger.id,
    )


def _sign(secret: str) -> dict[str, str]:
    return {"X-Webhook-Signature": hmac.new(secret.encode(), BODY, hashlib.sha256).hexdigest()}


async def _create(app, trigger, webhook_type: str):
    return await _post(
        app,
        "/",
        {
            "name": "Inbound",
            "agent_id": str(trigger.agent_id),
            "trigger_type": "webhook",
            "webhook_type": webhook_type,
        },
    )


async def test_a_new_generic_webhook_only_accepts_requests_signed_with_the_shown_secret():
    secrets, trigger = _MemorySecrets(), _trigger("generic")
    response = await _create(_app(trigger, secrets), trigger, "generic")

    assert response.status_code == 201, response.text
    body = response.json()
    assert body["webhook_signing"] == "signed"
    shown = body["signing_secret"]
    assert await _accepted(trigger, secrets, _sign(shown)) is True
    assert await _accepted(trigger, secrets, {}) is False
    assert await _accepted(trigger, secrets, _sign("guessed")) is False


async def test_reading_the_trigger_never_shows_the_secret_again():
    secrets, trigger = _MemorySecrets(), _trigger("generic")
    app = _app(trigger, secrets)
    await _create(app, trigger, "generic")

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get(f"/v1/workspaces/acme/triggers/{trigger.id}")

    assert response.json()["signing_secret"] is None
    assert response.json()["webhook_signing"] == "signed"


async def test_rotating_signs_a_legacy_unsigned_webhook_and_retires_the_old_secret():
    secrets, trigger = _MemorySecrets(), _trigger("generic")
    app = _app(trigger, secrets)
    # Created before signing existed: nothing stored, anyone may post.
    assert await _accepted(trigger, secrets, {}) is None

    first = (await _post(app, f"/{trigger.id}/signing-secret")).json()["signing_secret"]
    assert await _accepted(trigger, secrets, {}) is False
    assert await _accepted(trigger, secrets, _sign(first)) is True

    second = (await _post(app, f"/{trigger.id}/signing-secret")).json()["signing_secret"]
    assert second != first
    assert await _accepted(trigger, secrets, _sign(first)) is False
    assert await _accepted(trigger, secrets, _sign(second)) is True


@pytest.mark.parametrize("webhook_type", ["gmail", "teams"])
async def test_providers_without_verification_are_reported_unsupported(webhook_type):
    secrets, trigger = _MemorySecrets(), _trigger(webhook_type)
    app = _app(trigger, secrets)
    response = await _create(app, trigger, webhook_type)

    assert response.status_code == 201, response.text
    assert response.json()["webhook_signing"] == "unsupported"
    assert response.json()["signing_secret"] is None
    rotate = await _post(app, f"/{trigger.id}/signing-secret")
    assert rotate.status_code == 400


async def test_an_inline_secret_is_not_silently_shadowed_by_a_generated_one():
    secrets = _MemorySecrets()
    trigger = _trigger("generic", {"signing_secret": "configured-inline"})
    response = await _post(_app(trigger, secrets), f"/{trigger.id}/signing-secret")

    assert response.status_code == 409
    assert secrets.values == {}
