apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-manager
  namespace: default
  labels:
    app: mcp-manager
    component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-manager
  labels:
    app: mcp-manager
    component: cluster-role
rules:
# Core resources for MCP instance management
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Events for debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
# Node information for environment detection
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Service account and token management
- apiGroups: [""]
  resources: ["serviceaccounts", "serviceaccounts/token"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-manager
  labels:
    app: mcp-manager
    component: cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-manager
subjects:
- kind: ServiceAccount
  name: mcp-manager
  namespace: default