{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentarea.fullname" . }}-backend-env
  labels:
    {{- include "agentarea.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- include "agentarea.backend.configVars" . | nindent 2 }}
  {{- include "agentarea.database.configVars" . | nindent 2 }}
  {{- include "agentarea.redis.configVars" . | nindent 2 }}
  {{- include "agentarea.storage.configVars" . | nindent 2 }}
  {{- include "agentarea.temporal.configVars" . | nindent 2 }}
  {{- include "agentarea.mcpManager.configVars" . | nindent 2 }}
{{- end }}
