{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.backend.configVars" -}}
PORT: "8000"
AGENTAREA_LOG_LEVEL: "info"
AGENTAREA_MCP_MANAGER_URL: "http://{{ include "agentarea.fullname" . }}-mcp-manager:{{ .Values.mcpManager.service.port }}"
AGENTAREA_MCP_TIMEOUT: "30"
API_HOST: "{{ .Values.global.api.host }}"
API_PORT: "{{ .Values.global.api.port }}"
AGENTAREA_API_URL: "{{ include "agentarea.backend.apiUrl" . }}"
API_AUTH_ENABLED: "{{ .Values.global.api.auth.enabled }}"
AGENTAREA_S3_PUBLIC_ENDPOINT: "{{ .Values.global.storage.publicEndpoint }}"
METRICS_ENABLED: "{{ .Values.global.monitoring.prometheus.enabled }}"
METRICS_PORT: "{{ .Values.global.monitoring.prometheus.port }}"
HEALTH_CHECK_ENABLED: "{{ .Values.global.monitoring.health.enabled }}"
HEALTH_CHECK_PORT: "{{ .Values.global.monitoring.health.port }}"
AGENTAREA_AUTH_ISSUER: "{{ .Values.kratos.jwt.issuer }}"
AGENTAREA_AUTH_AUDIENCE: "{{ .Values.kratos.jwt.audience }}"
AGENTAREA_AUTH_KRATOS_ADMIN_URL: "{{ include "agentarea.kratosAdminUrl" . }}"
AGENTAREA_APP_URL: "{{ include "agentarea.frontendUrl" . }}"
SMTP_CONNECTION_URI: "{{ .Values.kratos.smtp.connection_uri }}"
SMTP_FROM_EMAIL: "{{ .Values.kratos.smtp.from_address }}"
SMTP_FROM_NAME: "{{ .Values.kratos.smtp.from_name }}"
{{- end }}

{{- define "agentarea.backend.envs" }}
- name: PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: PORT
- name: AGENTAREA_LOG_LEVEL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_LOG_LEVEL
- name: AGENTAREA_MCP_MANAGER_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_MCP_MANAGER_URL
- name: AGENTAREA_MCP_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_MCP_TIMEOUT
- name: API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: API_HOST
- name: API_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: API_PORT
- name: AGENTAREA_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_API_URL
- name: API_AUTH_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: API_AUTH_ENABLED
- name: AGENTAREA_S3_PUBLIC_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_S3_PUBLIC_ENDPOINT
- name: METRICS_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: METRICS_ENABLED
- name: METRICS_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: METRICS_PORT
- name: HEALTH_CHECK_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: HEALTH_CHECK_ENABLED
- name: HEALTH_CHECK_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: HEALTH_CHECK_PORT
- name: AGENTAREA_AUTH_ISSUER
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_AUTH_ISSUER
- name: AGENTAREA_AUTH_AUDIENCE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_AUTH_AUDIENCE
- name: AGENTAREA_AUTH_KRATOS_ADMIN_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_AUTH_KRATOS_ADMIN_URL
- name: AGENTAREA_APP_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: AGENTAREA_APP_URL
- name: SMTP_CONNECTION_URI
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: SMTP_CONNECTION_URI
- name: SMTP_FROM_EMAIL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: SMTP_FROM_EMAIL
- name: SMTP_FROM_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-backend
      key: SMTP_FROM_NAME
{{- end }}

{{- define "agentarea.backend.secrets.envs" }}
- name: API_AUTH_HEADER_NAME
  value: {{ .Values.global.api.auth.headerName }}
- name: API_AUTH_HEADER_VALUE
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.application }}"
      key: api-auth-header-value
{{- if .Values.kratos.enabled }}
- name: AGENTAREA_AUTH_JWKS_B64
  valueFrom:
    secretKeyRef:
      name: {{ default (printf "%s-kratos-jwks" .Release.Name) .Values.kratos.secretName | quote }}
      key: jwks_b64
{{- end }}
{{- end }}
