{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.database.configVars" -}}
AGENTAREA_DB_HOST: "{{ include "agentarea.database.host" . }}"
AGENTAREA_DB_PORT: "{{ .Values.global.database.port }}"
AGENTAREA_DB_NAME: "{{ .Values.global.database.name }}"
AGENTAREA_DB_SSLMODE: "{{ .Values.global.database.sslMode }}"
{{- end }}

{{- define "agentarea.database.envs" }}
- name: AGENTAREA_DB_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-database
      key: AGENTAREA_DB_HOST
- name: AGENTAREA_DB_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-database
      key: AGENTAREA_DB_PORT
- name: AGENTAREA_DB_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-database
      key: AGENTAREA_DB_NAME
- name: AGENTAREA_DB_SSLMODE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-database
      key: AGENTAREA_DB_SSLMODE
- name: AGENTAREA_DB_URL
  value: postgresql://$(AGENTAREA_DB_USER):$(AGENTAREA_DB_PASSWORD)@$(AGENTAREA_DB_HOST):$(AGENTAREA_DB_PORT)/$(AGENTAREA_DB_NAME)?sslmode={{ .Values.global.database.sslMode }}
{{- end }}

{{- define "agentarea.database.secrets.envs" }}
- name: AGENTAREA_DB_USER
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.postgresql }}"
      key: username
- name: AGENTAREA_DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.postgresql }}"
      key: password
{{- end }}
