{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.frontend.configVars" -}}
PORT: "3000"
NODE_ENV: "production"
AGENTAREA_API_URL: "{{ include "agentarea.backend.url" . }}"
AGENTAREA_AUTH_KRATOS_ADMIN_URL: "{{ include "agentarea.kratosAdminUrl" . }}"
ORY_SDK_URL: "{{ include "agentarea.kratosPublicUrl" . }}"
ORY_BROWSER_URL: "{{ include "agentarea.kratosPublicBrowserUrl" . }}"
AGENTAREA_METRICS_ENABLED: "{{ .Values.global.monitoring.prometheus.enabled }}"
AGENTAREA_MCP_APPS_ORIGIN: "{{ .Values.global.webapp.appsSandboxUrl }}"
AGENTAREA_APP_ORIGIN: "{{ include "agentarea.frontendUrl" . }}"
{{- end }}

{{- define "agentarea.frontend.envs" }}
- name: PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: PORT
- name: NODE_ENV
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: NODE_ENV
- name: AGENTAREA_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: AGENTAREA_API_URL
- name: AGENTAREA_AUTH_KRATOS_ADMIN_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: AGENTAREA_AUTH_KRATOS_ADMIN_URL
- name: ORY_SDK_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: ORY_SDK_URL
- name: ORY_BROWSER_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: ORY_BROWSER_URL
- name: AGENTAREA_METRICS_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: AGENTAREA_METRICS_ENABLED
- name: AGENTAREA_MCP_APPS_ORIGIN
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: AGENTAREA_MCP_APPS_ORIGIN
- name: AGENTAREA_APP_ORIGIN
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-frontend
      key: AGENTAREA_APP_ORIGIN
{{- end }}
