{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.mcpManager.configVars" -}}
LOG_LEVEL: "INFO"
CORE_API_URL: "http://{{ include "agentarea.fullname" . }}-backend:8000"
SERVER_HOST: "0.0.0.0"
SERVER_PORT: "80"
BACKEND_TYPE: "kubernetes"
KUBERNETES_ENABLED: "true"
KUBERNETES_NAMESPACE: "{{ .Release.Namespace }}"
KUBERNETES_DOMAIN: "{{ .Values.mcpManager.domain | default "mcp.local" }}"
KUBERNETES_GATEWAY_NAME: "{{ .Values.mcpManager.gateway.name | default "envoy-gateway" }}"
KUBERNETES_GATEWAY_NAMESPACE: "{{ .Values.mcpManager.gateway.namespace | default "envoy-gateway-system" }}"
KUBERNETES_RUNTIME_CLASS: "{{ .Values.mcpManager.runtimeClass }}"
DEFAULT_ISOLATION_TIER: "{{ required "mcpManager.isolationTier is required" .Values.mcpManager.isolationTier }}"
MCP_ALLOWED_IMAGE_REPOSITORIES: "{{ join "," .Values.mcpManager.admission.allowedImageRepositories }}"
MCP_ALLOWED_COMMAND_PACKAGES: "{{ join "," .Values.mcpManager.admission.allowedCommandPackages }}"
KUBERNETES_KUBECONFIG: "{{ include "agentarea.mcpManager.executionKubeconfigPath" . }}"
KUBERNETES_POD_SERVICE_ACCOUNT_NAME: "{{ include "agentarea.mcpRuntimeServiceAccountName" . }}"
SANDBOX_WORKSPACE_PROVIDER: "s3"
SANDBOX_WORKSPACE_MAX_FILES: "{{ .Values.sandboxRuntime.workspace.maxFiles }}"
SANDBOX_WORKSPACE_MAX_FILE_BYTES: "{{ .Values.sandboxRuntime.workspace.maxFileBytes }}"
SANDBOX_WORKSPACE_MAX_BYTES: "{{ .Values.sandboxRuntime.workspace.maxBytes }}"
SANDBOX_MAX_EXECUTION_TIMEOUT_SECONDS: "{{ .Values.sandboxRuntime.maxExecutionTimeoutSeconds }}"
SANDBOX_DEFAULT_EXECUTION_TIMEOUT_SECONDS: "{{ .Values.sandboxRuntime.defaultExecutionTimeoutSeconds }}"
SANDBOX_EXECUTION_QUEUE_TIMEOUT: "{{ .Values.sandboxRuntime.executionQueueTimeout }}"
SANDBOX_EXECUTION_COMPLETION_GRACE: "{{ .Values.sandboxRuntime.executionCompletionGrace }}"
SANDBOX_WORKSPACE_SIGNED_URL_TTL: "{{ .Values.sandboxRuntime.workspace.signedUrlTTL }}"
SANDBOX_WORKSPACE_S3_FORCE_PATH_STYLE: "{{ .Values.sandboxRuntime.workspace.forcePathStyle }}"
KUBERNETES_SECURITY_RUN_AS_NON_ROOT: "true"
KUBERNETES_SECURITY_READ_ONLY_ROOT_FS: "true"
KUBERNETES_DEFAULT_CPU_REQUEST: "100m"
KUBERNETES_DEFAULT_CPU_LIMIT: "500m"
KUBERNETES_DEFAULT_MEMORY_REQUEST: "128Mi"
KUBERNETES_DEFAULT_MEMORY_LIMIT: "512Mi"
MCP_FEATURES_ENABLED: "{{ join "," .Values.mcpManager.features.enabled }}"
MCP_IDLE_TIMEOUT: "{{ if .Values.mcpManager.serverless.enabled }}{{ .Values.mcpManager.serverless.idleTimeout }}{{ else }}0{{ end }}"
MCP_IDLE_SWEEP_INTERVAL: "{{ .Values.mcpManager.serverless.sweepInterval }}"
MCP_REQUEST_LEASE_TTL: "{{ .Values.mcpManager.serverless.requestLeaseTTL }}"
MCP_GATEWAY_STARTUP_TIMEOUT: "{{ .Values.mcpManager.serverless.startupTimeout }}"
{{- end }}

{{- define "agentarea.mcpManager.envs" }}
- name: LOG_LEVEL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: LOG_LEVEL
- name: CORE_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: CORE_API_URL
- name: SERVER_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SERVER_HOST
- name: SERVER_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SERVER_PORT
- name: BACKEND_TYPE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: BACKEND_TYPE
- name: KUBERNETES_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_ENABLED
- name: KUBERNETES_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_NAMESPACE
- name: KUBERNETES_DOMAIN
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_DOMAIN
- name: KUBERNETES_GATEWAY_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_GATEWAY_NAME
- name: KUBERNETES_GATEWAY_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_GATEWAY_NAMESPACE
- name: KUBERNETES_RUNTIME_CLASS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_RUNTIME_CLASS
- name: DEFAULT_ISOLATION_TIER
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: DEFAULT_ISOLATION_TIER
- name: MCP_ALLOWED_IMAGE_REPOSITORIES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_ALLOWED_IMAGE_REPOSITORIES
- name: MCP_ALLOWED_COMMAND_PACKAGES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_ALLOWED_COMMAND_PACKAGES
- name: KUBERNETES_KUBECONFIG
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_KUBECONFIG
- name: KUBERNETES_POD_SERVICE_ACCOUNT_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_POD_SERVICE_ACCOUNT_NAME
- name: SANDBOX_WORKSPACE_PROVIDER
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_WORKSPACE_PROVIDER
- name: SANDBOX_WORKSPACE_MAX_FILES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_WORKSPACE_MAX_FILES
- name: SANDBOX_WORKSPACE_MAX_FILE_BYTES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_WORKSPACE_MAX_FILE_BYTES
- name: SANDBOX_WORKSPACE_MAX_BYTES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_WORKSPACE_MAX_BYTES
- name: SANDBOX_MAX_EXECUTION_TIMEOUT_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_MAX_EXECUTION_TIMEOUT_SECONDS
- name: SANDBOX_DEFAULT_EXECUTION_TIMEOUT_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_DEFAULT_EXECUTION_TIMEOUT_SECONDS
- name: SANDBOX_EXECUTION_QUEUE_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_EXECUTION_QUEUE_TIMEOUT
- name: SANDBOX_EXECUTION_COMPLETION_GRACE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_EXECUTION_COMPLETION_GRACE
- name: SANDBOX_WORKSPACE_SIGNED_URL_TTL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_WORKSPACE_SIGNED_URL_TTL
- name: SANDBOX_WORKSPACE_S3_FORCE_PATH_STYLE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: SANDBOX_WORKSPACE_S3_FORCE_PATH_STYLE
- name: KUBERNETES_SECURITY_RUN_AS_NON_ROOT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_SECURITY_RUN_AS_NON_ROOT
- name: KUBERNETES_SECURITY_READ_ONLY_ROOT_FS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_SECURITY_READ_ONLY_ROOT_FS
- name: KUBERNETES_DEFAULT_CPU_REQUEST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_DEFAULT_CPU_REQUEST
- name: KUBERNETES_DEFAULT_CPU_LIMIT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_DEFAULT_CPU_LIMIT
- name: KUBERNETES_DEFAULT_MEMORY_REQUEST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_DEFAULT_MEMORY_REQUEST
- name: KUBERNETES_DEFAULT_MEMORY_LIMIT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: KUBERNETES_DEFAULT_MEMORY_LIMIT
- name: MCP_FEATURES_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_FEATURES_ENABLED
- name: MCP_IDLE_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_IDLE_TIMEOUT
- name: MCP_IDLE_SWEEP_INTERVAL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_IDLE_SWEEP_INTERVAL
- name: MCP_REQUEST_LEASE_TTL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_REQUEST_LEASE_TTL
- name: MCP_GATEWAY_STARTUP_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-mcpmanager
      key: MCP_GATEWAY_STARTUP_TIMEOUT
{{- end }}
