{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.redis.configVars" -}}
AGENTAREA_REDIS_HOST: "{{ include "agentarea.redis.host" . }}"
AGENTAREA_REDIS_PORT: "{{ .Values.global.redis.port }}"
{{- end }}

{{- define "agentarea.redis.envs" }}
- name: AGENTAREA_REDIS_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-redis
      key: AGENTAREA_REDIS_HOST
- name: AGENTAREA_REDIS_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-redis
      key: AGENTAREA_REDIS_PORT
{{- end }}

{{- define "agentarea.redis.secrets.envs" }}
- name: AGENTAREA_REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.redis }}"
      key: redis-password
{{- end }}
