{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.redis.configVars" -}}
REDIS_HOST: "{{ include "agentarea.redis.host" . }}"
REDIS_PORT: "{{ .Values.global.redis.port }}"
{{- end }}

{{- define "agentarea.redis.envs" }}
- name: REDIS_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-redis
      key: REDIS_HOST
- name: REDIS_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-redis
      key: REDIS_PORT
{{- if not (index (default dict .Values.global.envVars) "REDIS_URL") }}
- name: REDIS_URL
  value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
{{- end }}
{{- end }}

{{- define "agentarea.redis.secrets.envs" }}
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.redis }}"
      key: redis-password
{{- end }}
