{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.storage.configVars" -}}
AGENTAREA_S3_REGION: "{{ .Values.global.storage.region }}"
AGENTAREA_S3_BUCKET: "{{ .Values.global.storage.bucket }}"
AGENTAREA_S3_ARTIFACTS_BUCKET: "{{ .Values.global.storage.bucket }}"
AGENTAREA_S3_ENDPOINT: "http://{{ include "agentarea.rustfs.host" . }}:9000"
{{- end }}

{{- define "agentarea.storage.envs" }}
- name: AGENTAREA_S3_REGION
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-storage
      key: AGENTAREA_S3_REGION
- name: AGENTAREA_S3_BUCKET
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-storage
      key: AGENTAREA_S3_BUCKET
- name: AGENTAREA_S3_ARTIFACTS_BUCKET
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-storage
      key: AGENTAREA_S3_ARTIFACTS_BUCKET
- name: AGENTAREA_S3_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-storage
      key: AGENTAREA_S3_ENDPOINT
{{- end }}

{{- define "agentarea.storage.secrets.envs" }}
{{ if .Values.rustfs.enabled }}
- name: AGENTAREA_S3_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.rustfs }}"
      key: root-user
- name: AGENTAREA_S3_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: "{{ .Values.global.secrets.rustfs }}"
      key: root-password
{{- end }}
{{- end }}
