{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.temporal.configVars" -}}
AGENTAREA_WF_TEMPORAL_URL: "{{ include "agentarea.temporal.host" . }}:{{ .Values.global.temporal.port }}"
AGENTAREA_WF_NAMESPACE: "{{ .Values.global.temporal.namespace }}"
AGENTAREA_WF_QUEUE: "{{ .Values.global.temporal.taskQueue }}"
{{- end }}

{{- define "agentarea.temporal.envs" }}
- name: AGENTAREA_WF_TEMPORAL_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-temporal
      key: AGENTAREA_WF_TEMPORAL_URL
- name: AGENTAREA_WF_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-temporal
      key: AGENTAREA_WF_NAMESPACE
- name: AGENTAREA_WF_QUEUE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-temporal
      key: AGENTAREA_WF_QUEUE
{{- end }}
