{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.temporal.configVars" -}}
TEMPORAL_ADDRESS: "{{ include "agentarea.temporal.host" . }}:{{ .Values.global.temporal.port }}"
TEMPORAL_NAMESPACE: "{{ .Values.global.temporal.namespace }}"
AGENTAREA_TEMPORAL_QUEUE: "{{ .Values.global.temporal.taskQueue }}"
{{- end }}

{{- define "agentarea.temporal.envs" }}
- name: TEMPORAL_ADDRESS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-temporal
      key: TEMPORAL_ADDRESS
- name: TEMPORAL_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-temporal
      key: TEMPORAL_NAMESPACE
- name: AGENTAREA_TEMPORAL_QUEUE
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-temporal
      key: AGENTAREA_TEMPORAL_QUEUE
{{- end }}
