{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.worker.configVars" -}}
AGENTAREA_WF_MAX_ACTIVITIES: "10"
AGENTAREA_WF_MAX_WORKFLOWS: "5"
AGENTAREA_TASK_DISCOVERY_ENABLED: "true"
AGENTAREA_DEBUG: "false"
AGENTAREA_ENV: "production"
AGENTAREA_MCP_MANAGER_URL: "http://{{ include "agentarea.fullname" . }}-mcp-manager:{{ .Values.mcpManager.service.port }}"
{{- end }}

{{- define "agentarea.worker.envs" }}
- name: AGENTAREA_WF_MAX_ACTIVITIES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_WF_MAX_ACTIVITIES
- name: AGENTAREA_WF_MAX_WORKFLOWS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_WF_MAX_WORKFLOWS
- name: AGENTAREA_TASK_DISCOVERY_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_TASK_DISCOVERY_ENABLED
- name: AGENTAREA_DEBUG
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_DEBUG
- name: AGENTAREA_ENV
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_ENV
- name: AGENTAREA_MCP_MANAGER_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_MCP_MANAGER_URL
{{- end }}
