{{- if .Values.worker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentarea.fullname" . }}-worker-env
  labels:
    {{- include "agentarea.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
data:
  {{- include "agentarea.worker.configVars" . | nindent 2 }}
  {{- include "agentarea.database.configVars" . | nindent 2 }}
  {{- include "agentarea.redis.configVars" . | nindent 2 }}
  {{- include "agentarea.temporal.configVars" . | nindent 2 }}
{{- end }}
