{{/*
AUTOGENERATED FILE - DO NOT EDIT.
Generated by scripts/generate_env_tpls.py from charts/agentarea/config.yaml
*/}}

{{- define "agentarea.worker.configVars" -}}
AGENTAREA_TEMPORAL_MAX_ACTIVITIES: "10"
AGENTAREA_TEMPORAL_MAX_WORKFLOWS: "5"
AGENTAREA_DEBUG: "false"
AGENTAREA_ENV: "production"
AGENTAREA_MCP_MANAGER_URL: "http://{{ include "agentarea.fullname" . }}-mcp-manager:{{ .Values.mcpManager.service.port }}"
AGENTAREA_WORKER_HEALTH_PORT: "{{ .Values.worker.healthPort }}"
{{- end }}

{{- define "agentarea.worker.envs" }}
- name: AGENTAREA_TEMPORAL_MAX_ACTIVITIES
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_TEMPORAL_MAX_ACTIVITIES
- name: AGENTAREA_TEMPORAL_MAX_WORKFLOWS
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_TEMPORAL_MAX_WORKFLOWS
- name: AGENTAREA_DEBUG
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_DEBUG
- name: AGENTAREA_ENV
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_ENV
- name: AGENTAREA_MCP_MANAGER_URL
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_MCP_MANAGER_URL
- name: AGENTAREA_WORKER_HEALTH_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ include "agentarea.fullname" . }}-env-worker
      key: AGENTAREA_WORKER_HEALTH_PORT
{{- end }}
