"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Download, FileText } from "lucide-react";
import { LoadingSpinner } from "@/components/LoadingSpinner";
import { Button } from "@/components/ui/button";

interface TaskData {
  id: string;
  agent_id: string;
  status: string;
}

interface TaskStatus {
  artifacts?: unknown[];
}

export default function TaskArtifactsPage() {
  const params = useParams();
  const id = Array.isArray(params.id) ? params.id[0] : (params.id as string);

  const [task, setTask] = useState<TaskData | null>(null);
  const [taskStatus, setTaskStatus] = useState<TaskStatus | null>(null);
  const [loading, setLoading] = useState(true);

  const loadTask = useCallback(async () => {
    try {
      setLoading(true);
      const { getAllTasks, getAgentTaskStatus } = await import(
        "@/lib/browser-api"
      );
      const { data: allTasks } = await getAllTasks();
      const foundTask = allTasks?.find((t: any) => t.id?.toString() === id);

      if (foundTask) {
        setTask({
          id: foundTask.id.toString(),
          agent_id: foundTask.agent_id.toString(),
          status: foundTask.status,
        });

        const statusResponse = await getAgentTaskStatus(
          foundTask.agent_id.toString(),
          foundTask.id.toString()
        );
        if (!statusResponse.error && statusResponse.data) {
          setTaskStatus(statusResponse.data as TaskStatus);
        }
      }
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadTask();
  }, [loadTask]);

  if (loading) {
    return (
      <div className="p-8">
        <LoadingSpinner />
      </div>
    );
  }

  const isActive = task ? ["running", "paused"].includes(task.status) : false;

  return (
    <div className="main-content">
      <h3 className="text-lg font-semibold">Artifacts</h3>
      <p className="note">
        Files and outputs generated by this task
      </p>
        {taskStatus?.artifacts && taskStatus.artifacts.length > 0 ? (
          <div className="space-y-4">
            {taskStatus.artifacts.map((artifact, index) => (
              <div
                key={index}
                className="flex items-center justify-between rounded-lg border p-4"
              >
                <div className="flex items-center gap-3">
                  <FileText className="h-8 w-8 text-primary" />
                  <div>
                    <p className="font-medium">
                      {typeof artifact === "string"
                        ? artifact
                        : `Artifact ${index + 1}`}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      Generated by task execution
                    </p>
                  </div>
                </div>
                <Button variant="outline" size="sm" className="gap-1" disabled>
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              </div>
            ))}
          </div>
        ) : (
          <div className="py-12 text-center">
            <FileText className="mx-auto mb-4 h-16 w-16 text-muted-foreground opacity-50" />
            <h3 className="mb-2 text-lg font-semibold">No Artifacts</h3>
            <p className="text-muted-foreground">
              {isActive
                ? "Artifacts will appear here as the task generates outputs."
                : "This task did not generate any artifacts."}
            </p>
          </div>
        )}
    </div>
  );
}

