import {type CommandSpec} from './types.js';

export const registry: CommandSpec[] = [
	// agents
	{
		noun: 'agents',
		verb: 'list',
		fn: 'listAgentsV1AgentsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List all agents',
	},
	{
		noun: 'agents',
		verb: 'create',
		fn: 'createAgentV1AgentsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an agent',
	},
	{
		noun: 'agents',
		verb: 'tools',
		fn: 'getAllToolsV1AgentsToolsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get all tools across agents',
	},
	{
		noun: 'agents',
		verb: 'get',
		fn: 'getAgentV1AgentsAgentIdGet',
		method: 'GET',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Get an agent by ID',
	},
	{
		noun: 'agents',
		verb: 'update',
		aliases: ['patch'],
		fn: 'updateAgentV1AgentsAgentIdPatch',
		method: 'PATCH',
		pathParams: ['agent_id'],
		body: true,
		summary: 'Update an agent',
	},
	{
		noun: 'agents',
		verb: 'delete',
		aliases: ['rm'],
		fn: 'deleteAgentV1AgentsAgentIdDelete',
		method: 'DELETE',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Delete an agent',
	},
	{
		noun: 'agents',
		verb: 'install',
		fn: 'installAgentV1AgentsAgentIdInstallPost',
		method: 'POST',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Install an agent from catalog',
	},
	{
		noun: 'agents',
		verb: 'overview',
		fn: 'getAgentOverviewV1AgentsAgentIdOverviewGet',
		method: 'GET',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Get agent overview',
	},

	// tasks
	{
		noun: 'tasks',
		verb: 'submit',
		fn: 'createTaskForAgentWithStreamV1AgentsAgentIdTasksPost',
		method: 'POST',
		pathParams: ['agent_id'],
		body: true,
		summary: 'Submit a task to an agent (streaming)',
	},
	{
		noun: 'tasks',
		verb: 'list',
		fn: 'listAgentTasksV1AgentsAgentIdTasksGet',
		method: 'GET',
		pathParams: ['agent_id'],
		body: false,
		summary: 'List tasks for an agent',
	},
	{
		noun: 'tasks',
		verb: 'submit-sync',
		fn: 'createTaskForAgentSyncV1AgentsAgentIdTasksSyncPost',
		method: 'POST',
		pathParams: ['agent_id'],
		body: true,
		summary: 'Submit a task synchronously',
	},
	{
		noun: 'tasks',
		verb: 'get',
		fn: 'getAgentTaskV1AgentsAgentIdTasksTaskIdGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Get a task',
	},
	{
		noun: 'tasks',
		verb: 'cancel',
		fn: 'cancelAgentTaskV1AgentsAgentIdTasksTaskIdDelete',
		method: 'DELETE',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Cancel a task',
	},
	{
		noun: 'tasks',
		verb: 'status',
		fn: 'getAgentTaskStatusV1AgentsAgentIdTasksTaskIdStatusGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Get task status',
	},
	{
		noun: 'tasks',
		verb: 'artifacts',
		fn: 'listTaskArtifactsV1AgentsAgentIdTasksTaskIdArtifactsGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'List task artifacts',
	},
	{
		noun: 'tasks',
		verb: 'artifact-download',
		fn: 'downloadTaskArtifactV1AgentsAgentIdTasksTaskIdArtifactsFilesArtifactPathGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id', 'artifact_path'],
		body: false,
		summary: 'Download a task artifact file',
	},
	{
		noun: 'tasks',
		verb: 'summary',
		fn: 'getTaskSummaryV1AgentsAgentIdTasksTaskIdSummaryGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Get task summary',
	},
	{
		noun: 'tasks',
		verb: 'pause',
		fn: 'pauseAgentTaskV1AgentsAgentIdTasksTaskIdPausePost',
		method: 'POST',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Pause a task',
	},
	{
		noun: 'tasks',
		verb: 'resume',
		fn: 'resumeAgentTaskV1AgentsAgentIdTasksTaskIdResumePost',
		method: 'POST',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Resume a paused task',
	},
	{
		noun: 'tasks',
		verb: 'a2ui-action',
		fn: 'sendA2UiActionV1AgentsAgentIdTasksTaskIdA2UiActionPost',
		method: 'POST',
		pathParams: ['agent_id', 'task_id'],
		body: true,
		summary: 'Send an agent-to-UI action',
	},
	{
		noun: 'tasks',
		verb: 'input',
		fn: 'submitTaskInputV1AgentsAgentIdTasksTaskIdInputPost',
		method: 'POST',
		pathParams: ['agent_id', 'task_id'],
		body: true,
		summary: 'Submit input to a waiting task',
	},
	{
		noun: 'tasks',
		verb: 'command',
		fn: 'sendTaskCommandV1AgentsAgentIdTasksTaskIdCommandPost',
		method: 'POST',
		pathParams: ['agent_id', 'task_id'],
		body: true,
		summary: 'Send a command to a task',
	},
	{
		noun: 'tasks',
		verb: 'resolve-escalation',
		fn: 'resolveTaskEscalationV1AgentsAgentIdTasksTaskIdResolveEscalationPost',
		method: 'POST',
		pathParams: ['agent_id', 'task_id'],
		body: true,
		summary: 'Resolve a task escalation',
	},
	{
		noun: 'tasks',
		verb: 'events',
		fn: 'getTaskEventsV1AgentsAgentIdTasksTaskIdEventsGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Get task events',
	},
	{
		noun: 'tasks',
		verb: 'events-stream',
		fn: 'streamTaskEventsV1AgentsAgentIdTasksTaskIdEventsStreamGet',
		method: 'GET',
		pathParams: ['agent_id', 'task_id'],
		body: false,
		summary: 'Stream task events via SSE',
	},
	{
		noun: 'tasks',
		verb: 'list-all',
		fn: 'getAllTasksV1TasksGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List all tasks across all agents',
	},
	{
		noun: 'tasks',
		verb: 'get-by-id',
		fn: 'getTaskByIdV1TasksTaskIdGet',
		method: 'GET',
		pathParams: ['task_id'],
		body: false,
		summary: 'Get a task by ID (cross-agent)',
	},

	// wallet
	{
		noun: 'wallet',
		verb: 'create',
		fn: 'createWalletV1AgentsAgentIdWalletPost',
		method: 'POST',
		pathParams: ['agent_id'],
		body: true,
		summary: 'Create a wallet for an agent',
	},
	{
		noun: 'wallet',
		verb: 'get',
		fn: 'getWalletV1AgentsAgentIdWalletGet',
		method: 'GET',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Get an agent wallet',
	},
	{
		noun: 'wallet',
		verb: 'update',
		fn: 'updateWalletV1AgentsAgentIdWalletPut',
		method: 'PUT',
		pathParams: ['agent_id'],
		body: true,
		summary: 'Update an agent wallet',
	},
	{
		noun: 'wallet',
		verb: 'delete',
		fn: 'deleteWalletV1AgentsAgentIdWalletDelete',
		method: 'DELETE',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Delete an agent wallet',
	},
	{
		noun: 'wallet',
		verb: 'balance',
		fn: 'getWalletBalanceV1AgentsAgentIdWalletBalanceGet',
		method: 'GET',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Get wallet balance',
	},
	{
		noun: 'wallet',
		verb: 'payments',
		fn: 'getPaymentHistoryV1AgentsAgentIdWalletPaymentsGet',
		method: 'GET',
		pathParams: ['agent_id'],
		body: false,
		summary: 'Get wallet payment history',
	},
	{
		noun: 'wallet',
		verb: 'fund',
		fn: 'fundWalletV1AgentsAgentIdWalletFundPost',
		method: 'POST',
		pathParams: ['agent_id'],
		body: true,
		summary: 'Fund an agent wallet',
	},

	// policies
	{
		noun: 'policies',
		verb: 'list',
		fn: 'listPolicyRulesV1PoliciesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List policy rules',
	},
	{
		noun: 'policies',
		verb: 'create',
		fn: 'createPolicyRuleV1PoliciesPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a policy rule',
	},
	{
		noun: 'policies',
		verb: 'get',
		fn: 'getPolicyRuleV1PoliciesRuleIdGet',
		method: 'GET',
		pathParams: ['rule_id'],
		body: false,
		summary: 'Get a policy rule',
	},
	{
		noun: 'policies',
		verb: 'update',
		fn: 'updatePolicyRuleV1PoliciesRuleIdPatch',
		method: 'PATCH',
		pathParams: ['rule_id'],
		body: true,
		summary: 'Update a policy rule',
	},
	{
		noun: 'policies',
		verb: 'delete',
		fn: 'deletePolicyRuleV1PoliciesRuleIdDelete',
		method: 'DELETE',
		pathParams: ['rule_id'],
		body: false,
		summary: 'Delete a policy rule',
	},

	// governance
	{
		noun: 'governance',
		verb: 'preview-policy',
		fn: 'previewEffectivePolicyV1GovernanceEffectivePolicyPreviewPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Preview effective policy for a subject',
	},
	{
		noun: 'governance',
		verb: 'task-snapshot',
		fn: 'getTaskPolicySnapshotV1GovernanceTaskPolicySnapshotsTaskIdGet',
		method: 'GET',
		pathParams: ['task_id'],
		body: false,
		summary: 'Get policy snapshot for a task',
	},

	// access
	{
		noun: 'access',
		verb: 'graph',
		fn: 'getGraphV1AccessControlGraphGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get the access control graph',
	},
	{
		noun: 'access',
		verb: 'relationships-list',
		fn: 'listRelationshipsV1AccessControlRelationshipsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List access relationships',
	},
	{
		noun: 'access',
		verb: 'relationship-create',
		fn: 'createRelationshipV1AccessControlRelationshipsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an access relationship',
	},
	{
		noun: 'access',
		verb: 'relationship-delete',
		fn: 'deleteRelationshipV1AccessControlRelationshipsDelete',
		method: 'DELETE',
		pathParams: [],
		body: true,
		summary: 'Delete an access relationship',
	},
	{
		noun: 'access',
		verb: 'check',
		fn: 'checkPermissionV1AccessControlCheckPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Check a permission',
	},
	{
		noun: 'access',
		verb: 'resolve',
		fn: 'resolveAccessV1AccessControlResolvePost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Resolve access for a subject',
	},
	{
		noun: 'access',
		verb: 'sync',
		fn: 'syncGrantsV1AccessControlSyncPost',
		method: 'POST',
		pathParams: [],
		body: false,
		summary: 'Sync access grants',
	},
	{
		noun: 'access',
		verb: 'tool-grants-list',
		fn: 'listToolAccessGrantsV1ToolAccessGrantsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List tool access grants',
	},
	{
		noun: 'access',
		verb: 'tool-grant',
		fn: 'grantToolAccessV1ToolAccessGrantsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Grant tool access',
	},
	{
		noun: 'access',
		verb: 'tool-revoke',
		fn: 'revokeToolAccessV1ToolAccessGrantsDelete',
		method: 'DELETE',
		pathParams: [],
		body: true,
		summary: 'Revoke tool access',
	},
	{
		noun: 'access',
		verb: 'tool-check',
		fn: 'checkToolAccessV1ToolAccessChecksPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Check tool access',
	},

	// mcp-servers
	{
		noun: 'mcp-servers',
		verb: 'list',
		fn: 'listMcpServersV1McpServersGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List MCP servers',
	},
	{
		noun: 'mcp-servers',
		verb: 'create',
		fn: 'createMcpServerV1McpServersPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an MCP server',
	},
	{
		noun: 'mcp-servers',
		verb: 'get',
		fn: 'getMcpServerV1McpServersServerIdGet',
		method: 'GET',
		pathParams: ['server_id'],
		body: false,
		summary: 'Get an MCP server',
	},
	{
		noun: 'mcp-servers',
		verb: 'update',
		fn: 'updateMcpServerV1McpServersServerIdPatch',
		method: 'PATCH',
		pathParams: ['server_id'],
		body: true,
		summary: 'Update an MCP server',
	},
	{
		noun: 'mcp-servers',
		verb: 'delete',
		fn: 'deleteMcpServerV1McpServersServerIdDelete',
		method: 'DELETE',
		pathParams: ['server_id'],
		body: false,
		summary: 'Delete an MCP server',
	},
	{
		noun: 'mcp-servers',
		verb: 'deploy',
		fn: 'deployMcpServerV1McpServersServerIdDeployPost',
		method: 'POST',
		pathParams: ['server_id'],
		body: false,
		summary: 'Deploy an MCP server',
	},

	// mcp-instances
	{
		noun: 'mcp-instances',
		verb: 'list',
		fn: 'listMcpServerInstancesV1McpServerInstancesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List MCP server instances',
	},
	{
		noun: 'mcp-instances',
		verb: 'create',
		fn: 'createMcpServerInstanceV1McpServerInstancesPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an MCP server instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'create-with-spec',
		fn: 'createMcpServerConnectionV1McpServerInstancesWithSpecPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an MCP instance with inline spec',
	},
	{
		noun: 'mcp-instances',
		verb: 'validate',
		fn: 'validateInstanceSpecV1McpServerInstancesValidatePost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Validate an MCP instance spec',
	},
	{
		noun: 'mcp-instances',
		verb: 'validate-connection',
		fn: 'validateConnectionV1McpServerInstancesValidateConnectionPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Validate an MCP server connection',
	},
	{
		noun: 'mcp-instances',
		verb: 'check',
		fn: 'checkMcpServerInstanceConfigurationV1McpServerInstancesCheckPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Check MCP instance configuration',
	},
	{
		noun: 'mcp-instances',
		verb: 'get',
		fn: 'getMcpServerInstanceV1McpServerInstancesInstanceIdGet',
		method: 'GET',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Get an MCP server instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'update',
		fn: 'updateMcpServerInstanceV1McpServerInstancesInstanceIdPatch',
		method: 'PATCH',
		pathParams: ['instance_id'],
		body: true,
		summary: 'Update an MCP server instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'delete',
		fn: 'deleteMcpServerInstanceV1McpServerInstancesInstanceIdDelete',
		method: 'DELETE',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Delete an MCP server instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'verify',
		fn: 'verifyMcpServerInstanceV1McpServerInstancesInstanceIdVerifyPost',
		method: 'POST',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Verify an MCP server instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'discover-tools',
		fn: 'discoverMcpServerInstanceToolsV1McpServerInstancesInstanceIdDiscoverToolsPost',
		method: 'POST',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Discover tools on an MCP server instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'environment',
		fn: 'getInstanceEnvironmentV1McpServerInstancesInstanceIdEnvironmentGet',
		method: 'GET',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Get MCP instance environment',
	},
	{
		noun: 'mcp-instances',
		verb: 'oauth-link',
		fn: 'createOauthLinkV1McpServerInstancesInstanceIdOauthLinkPost',
		method: 'POST',
		pathParams: ['instance_id'],
		body: true,
		summary: 'Create an OAuth link for an MCP instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'oauth-links',
		fn: 'listOauthLinksV1McpServerInstancesInstanceIdOauthLinksGet',
		method: 'GET',
		pathParams: ['instance_id'],
		body: false,
		summary: 'List OAuth links for an MCP instance',
	},
	{
		noun: 'mcp-instances',
		verb: 'probe',
		fn: 'probeInstanceAuthV1McpServerInstancesInstanceIdProbePost',
		method: 'POST',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Probe MCP instance auth',
	},
	{
		noun: 'mcp-instances',
		verb: 'test-auth',
		fn: 'runTestAuthV1McpServerInstancesInstanceIdTestAuthPost',
		method: 'POST',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Run auth test on an MCP instance',
	},

	// mcp-auth
	{
		noun: 'mcp-auth',
		verb: 'list',
		fn: 'listMcpAuthConfigsV1McpAuthConfigsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List MCP auth configs',
	},
	{
		noun: 'mcp-auth',
		verb: 'create',
		fn: 'createMcpAuthConfigV1McpAuthConfigsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an MCP auth config',
	},
	{
		noun: 'mcp-auth',
		verb: 'get',
		fn: 'getMcpAuthConfigV1McpAuthConfigsConfigIdGet',
		method: 'GET',
		pathParams: ['config_id'],
		body: false,
		summary: 'Get an MCP auth config',
	},
	{
		noun: 'mcp-auth',
		verb: 'update',
		fn: 'updateMcpAuthConfigV1McpAuthConfigsConfigIdPut',
		method: 'PUT',
		pathParams: ['config_id'],
		body: true,
		summary: 'Update an MCP auth config',
	},
	{
		noun: 'mcp-auth',
		verb: 'delete',
		fn: 'deleteMcpAuthConfigV1McpAuthConfigsConfigIdDelete',
		method: 'DELETE',
		pathParams: ['config_id'],
		body: false,
		summary: 'Delete an MCP auth config',
	},

	// mcp-oauth-links
	{
		noun: 'mcp-oauth-links',
		verb: 'create',
		fn: 'createOauthLinkV1McpOauthLinksPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an MCP OAuth link',
	},
	{
		noun: 'mcp-oauth-links',
		verb: 'list-for-instance',
		fn: 'listOauthLinksForInstanceV1McpOauthLinksInstanceInstanceIdGet',
		method: 'GET',
		pathParams: ['instance_id'],
		body: false,
		summary: 'List OAuth links for an instance',
	},
	{
		noun: 'mcp-oauth-links',
		verb: 'get',
		fn: 'getOauthLinkV1McpOauthLinksLinkIdGet',
		method: 'GET',
		pathParams: ['link_id'],
		body: false,
		summary: 'Get an MCP OAuth link',
	},
	{
		noun: 'mcp-oauth-links',
		verb: 'revoke',
		fn: 'revokeOauthLinkV1McpOauthLinksLinkIdDelete',
		method: 'DELETE',
		pathParams: ['link_id'],
		body: false,
		summary: 'Revoke an MCP OAuth link',
	},

	// providers
	{
		noun: 'providers',
		verb: 'configs-list',
		fn: 'listProviderConfigsV1ProviderConfigsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List provider configs',
	},
	{
		noun: 'providers',
		verb: 'config-create',
		fn: 'createProviderConfigV1ProviderConfigsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a provider config',
	},
	{
		noun: 'providers',
		verb: 'configs-with-instances',
		fn: 'listProviderConfigsWithInstancesV1ProviderConfigsWithInstancesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List provider configs with model instances',
	},
	{
		noun: 'providers',
		verb: 'config-discover-preview',
		fn: 'discoverModelsPreviewV1ProviderConfigsDiscoverPreviewPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Preview model discovery for a provider config',
	},
	{
		noun: 'providers',
		verb: 'config-get',
		fn: 'getProviderConfigV1ProviderConfigsConfigIdGet',
		method: 'GET',
		pathParams: ['config_id'],
		body: false,
		summary: 'Get a provider config',
	},
	{
		noun: 'providers',
		verb: 'config-update',
		fn: 'updateProviderConfigV1ProviderConfigsConfigIdPut',
		method: 'PUT',
		pathParams: ['config_id'],
		body: true,
		summary: 'Update a provider config (full replace)',
	},
	{
		noun: 'providers',
		verb: 'config-patch',
		fn: 'patchProviderConfigV1ProviderConfigsConfigIdPatch',
		method: 'PATCH',
		pathParams: ['config_id'],
		body: true,
		summary: 'Patch a provider config',
	},
	{
		noun: 'providers',
		verb: 'config-delete',
		fn: 'deleteProviderConfigV1ProviderConfigsConfigIdDelete',
		method: 'DELETE',
		pathParams: ['config_id'],
		body: false,
		summary: 'Delete a provider config',
	},
	{
		noun: 'providers',
		verb: 'config-discover',
		fn: 'discoverModelsV1ProviderConfigsConfigIdDiscoverPost',
		method: 'POST',
		pathParams: ['config_id'],
		body: false,
		summary: 'Discover models for a provider config',
	},
	{
		noun: 'providers',
		verb: 'specs-list',
		fn: 'listProviderSpecsV1ProviderSpecsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List provider specs',
	},
	{
		noun: 'providers',
		verb: 'specs-with-models',
		fn: 'listProviderSpecsWithModelsV1ProviderSpecsWithModelsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List provider specs with models',
	},
	{
		noun: 'providers',
		verb: 'spec-get',
		fn: 'getProviderSpecV1ProviderSpecsProviderSpecIdGet',
		method: 'GET',
		pathParams: ['provider_spec_id'],
		body: false,
		summary: 'Get a provider spec',
	},
	{
		noun: 'providers',
		verb: 'spec-get-by-key',
		fn: 'getProviderSpecByKeyV1ProviderSpecsByKeyProviderKeyGet',
		method: 'GET',
		pathParams: ['provider_key'],
		body: false,
		summary: 'Get a provider spec by key',
	},

	// models
	{
		noun: 'models',
		verb: 'instances-list',
		fn: 'listModelInstancesV1ModelInstancesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List model instances',
	},
	{
		noun: 'models',
		verb: 'instance-create',
		fn: 'createModelInstanceV1ModelInstancesPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a model instance',
	},
	{
		noun: 'models',
		verb: 'instances-bulk',
		fn: 'createModelInstancesBulkV1ModelInstancesBulkPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Bulk create model instances',
	},
	{
		noun: 'models',
		verb: 'instance-get',
		fn: 'getModelInstanceV1ModelInstancesInstanceIdGet',
		method: 'GET',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Get a model instance',
	},
	{
		noun: 'models',
		verb: 'instance-delete',
		fn: 'deleteModelInstanceV1ModelInstancesInstanceIdDelete',
		method: 'DELETE',
		pathParams: ['instance_id'],
		body: false,
		summary: 'Delete a model instance',
	},
	{
		noun: 'models',
		verb: 'instance-test',
		fn: 'validateModelInstanceV1ModelInstancesTestPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Test/validate a model instance',
	},
	{
		noun: 'models',
		verb: 'specs-list',
		fn: 'listModelSpecsV1ModelSpecsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List model specs',
	},
	{
		noun: 'models',
		verb: 'spec-create',
		fn: 'createModelSpecV1ModelSpecsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a model spec',
	},
	{
		noun: 'models',
		verb: 'spec-get',
		fn: 'getModelSpecV1ModelSpecsModelSpecIdGet',
		method: 'GET',
		pathParams: ['model_spec_id'],
		body: false,
		summary: 'Get a model spec',
	},
	{
		noun: 'models',
		verb: 'spec-update',
		fn: 'updateModelSpecV1ModelSpecsModelSpecIdPatch',
		method: 'PATCH',
		pathParams: ['model_spec_id'],
		body: true,
		summary: 'Update a model spec',
	},
	{
		noun: 'models',
		verb: 'spec-delete',
		fn: 'deleteModelSpecV1ModelSpecsModelSpecIdDelete',
		method: 'DELETE',
		pathParams: ['model_spec_id'],
		body: false,
		summary: 'Delete a model spec',
	},
	{
		noun: 'models',
		verb: 'spec-upsert',
		fn: 'upsertModelSpecV1ModelSpecsUpsertPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Upsert a model spec',
	},
	{
		noun: 'models',
		verb: 'specs-by-provider',
		fn: 'listModelSpecsByProviderV1ModelSpecsByProviderProviderSpecIdGet',
		method: 'GET',
		pathParams: ['provider_spec_id'],
		body: false,
		summary: 'List model specs by provider',
	},
	{
		noun: 'models',
		verb: 'spec-get-by-name',
		fn: 'getModelSpecByProviderAndNameV1ModelSpecsByProviderProviderSpecIdModelNameGet',
		method: 'GET',
		pathParams: ['provider_spec_id', 'model_name'],
		body: false,
		summary: 'Get a model spec by provider and name',
	},

	// triggers
	{
		noun: 'triggers',
		verb: 'list',
		fn: 'listTriggersV1TriggersGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List triggers',
	},
	{
		noun: 'triggers',
		verb: 'create',
		fn: 'createTriggerV1TriggersPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a trigger',
	},
	{
		noun: 'triggers',
		verb: 'catalog',
		fn: 'getCatalogV1TriggersCatalogGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get trigger catalog',
	},
	{
		noun: 'triggers',
		verb: 'channels',
		fn: 'getChannelEventsV1TriggersChannelsEventsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get channel events for triggers',
	},
	{
		noun: 'triggers',
		verb: 'get',
		fn: 'getTriggerV1TriggersTriggerIdGet',
		method: 'GET',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Get a trigger',
	},
	{
		noun: 'triggers',
		verb: 'update',
		fn: 'updateTriggerV1TriggersTriggerIdPut',
		method: 'PUT',
		pathParams: ['trigger_id'],
		body: true,
		summary: 'Update a trigger',
	},
	{
		noun: 'triggers',
		verb: 'delete',
		fn: 'deleteTriggerV1TriggersTriggerIdDelete',
		method: 'DELETE',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Delete a trigger',
	},
	{
		noun: 'triggers',
		verb: 'enable',
		fn: 'enableTriggerV1TriggersTriggerIdEnablePost',
		method: 'POST',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Enable a trigger',
	},
	{
		noun: 'triggers',
		verb: 'disable',
		fn: 'disableTriggerV1TriggersTriggerIdDisablePost',
		method: 'POST',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Disable a trigger',
	},
	{
		noun: 'triggers',
		verb: 'execute',
		fn: 'executeTriggerV1TriggersTriggerIdExecutePost',
		method: 'POST',
		pathParams: ['trigger_id'],
		body: true,
		summary: 'Execute a trigger manually',
	},
	{
		noun: 'triggers',
		verb: 'executions',
		fn: 'getExecutionHistoryV1TriggersTriggerIdExecutionsGet',
		method: 'GET',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Get trigger execution history',
	},
	{
		noun: 'triggers',
		verb: 'status',
		fn: 'getTriggerStatusV1TriggersTriggerIdStatusGet',
		method: 'GET',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Get trigger status',
	},
	{
		noun: 'triggers',
		verb: 'metrics',
		fn: 'getExecutionMetricsV1TriggersTriggerIdMetricsGet',
		method: 'GET',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Get trigger execution metrics',
	},
	{
		noun: 'triggers',
		verb: 'timeline',
		fn: 'getExecutionTimelineV1TriggersTriggerIdTimelineGet',
		method: 'GET',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Get trigger execution timeline',
	},
	{
		noun: 'triggers',
		verb: 'correlations',
		fn: 'getExecutionCorrelationsV1TriggersTriggerIdCorrelationsGet',
		method: 'GET',
		pathParams: ['trigger_id'],
		body: false,
		summary: 'Get trigger execution correlations',
	},

	// workspace
	{
		noun: 'workspace',
		verb: 'list',
		fn: 'listWorkspacesV1WorkspacesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List workspaces',
	},
	{
		noun: 'workspace',
		verb: 'create',
		fn: 'createWorkspaceV1WorkspacesPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a workspace',
	},
	{
		noun: 'workspace',
		verb: 'members',
		fn: 'listMembersV1WorkspacesWorkspaceIdMembersGet',
		method: 'GET',
		pathParams: ['workspace_id'],
		body: false,
		summary: 'List workspace members',
	},
	{
		noun: 'workspace',
		verb: 'member-remove',
		fn: 'removeMemberV1WorkspacesWorkspaceIdMembersUserIdDelete',
		method: 'DELETE',
		pathParams: ['workspace_id', 'user_id'],
		body: false,
		summary: 'Remove a workspace member',
	},
	{
		noun: 'workspace',
		verb: 'invite',
		fn: 'createInvitationV1WorkspacesWorkspaceIdInvitationsPost',
		method: 'POST',
		pathParams: ['workspace_id'],
		body: true,
		summary: 'Invite a user to a workspace',
	},
	{
		noun: 'workspace',
		verb: 'invitations',
		fn: 'listInvitationsV1WorkspacesWorkspaceIdInvitationsGet',
		method: 'GET',
		pathParams: ['workspace_id'],
		body: false,
		summary: 'List workspace invitations',
	},
	{
		noun: 'workspace',
		verb: 'invitation-revoke',
		fn: 'revokeInvitationV1WorkspacesWorkspaceIdInvitationsInvitationIdDelete',
		method: 'DELETE',
		pathParams: ['workspace_id', 'invitation_id'],
		body: false,
		summary: 'Revoke a workspace invitation',
	},
	{
		noun: 'workspace',
		verb: 'dashboard',
		fn: 'getDashboardV1WorkspaceDashboardGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get workspace dashboard',
	},
	{
		noun: 'workspace',
		verb: 'settings',
		fn: 'getWorkspaceSettingsV1WorkspaceSettingsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get workspace settings',
	},
	{
		noun: 'workspace',
		verb: 'settings-update',
		fn: 'updateWorkspaceSettingsV1WorkspaceSettingsPut',
		method: 'PUT',
		pathParams: [],
		body: true,
		summary: 'Update workspace settings',
	},
	{
		noun: 'workspace',
		verb: 'export',
		fn: 'exportWorkspaceConfigV1WorkspaceExportGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Export workspace config',
	},
	{
		noun: 'workspace',
		verb: 'import',
		fn: 'importWorkspaceConfigV1WorkspaceImportPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Import workspace config',
	},
	{
		noun: 'workspace',
		verb: 'import-file',
		fn: 'importWorkspaceConfigFileV1WorkspaceImportFilePost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Import workspace config from a file upload',
	},

	// invitations
	{
		noun: 'invitations',
		verb: 'accept',
		fn: 'acceptInvitationV1InvitationsAcceptPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Accept a workspace invitation',
	},

	// projects
	{
		noun: 'projects',
		verb: 'list',
		fn: 'listProjectsV1ProjectsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List projects',
	},
	{
		noun: 'projects',
		verb: 'create',
		fn: 'createProjectV1ProjectsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a project',
	},
	{
		noun: 'projects',
		verb: 'get',
		fn: 'getProjectV1ProjectsProjectIdGet',
		method: 'GET',
		pathParams: ['project_id'],
		body: false,
		summary: 'Get a project',
	},
	{
		noun: 'projects',
		verb: 'update',
		fn: 'updateProjectV1ProjectsProjectIdPatch',
		method: 'PATCH',
		pathParams: ['project_id'],
		body: true,
		summary: 'Update a project',
	},
	{
		noun: 'projects',
		verb: 'delete',
		fn: 'deleteProjectV1ProjectsProjectIdDelete',
		method: 'DELETE',
		pathParams: ['project_id'],
		body: false,
		summary: 'Delete a project',
	},
	{
		noun: 'projects',
		verb: 'add-agent',
		fn: 'addAgentToProjectV1ProjectsProjectIdAgentsPost',
		method: 'POST',
		pathParams: ['project_id'],
		body: true,
		summary: 'Add an agent to a project',
	},
	{
		noun: 'projects',
		verb: 'remove-agent',
		fn: 'removeAgentFromProjectV1ProjectsProjectIdAgentsAgentIdDelete',
		method: 'DELETE',
		pathParams: ['project_id', 'agent_id'],
		body: false,
		summary: 'Remove an agent from a project',
	},
	{
		noun: 'projects',
		verb: 'add-mcp',
		fn: 'addMcpInstanceToProjectV1ProjectsProjectIdMcpInstancesPost',
		method: 'POST',
		pathParams: ['project_id'],
		body: true,
		summary: 'Add an MCP instance to a project',
	},
	{
		noun: 'projects',
		verb: 'remove-mcp',
		fn: 'removeMcpInstanceFromProjectV1ProjectsProjectIdMcpInstancesMcpInstanceIdDelete',
		method: 'DELETE',
		pathParams: ['project_id', 'mcp_instance_id'],
		body: false,
		summary: 'Remove an MCP instance from a project',
	},
	{
		noun: 'projects',
		verb: 'add-skill',
		fn: 'addSkillToProjectV1ProjectsProjectIdSkillsPost',
		method: 'POST',
		pathParams: ['project_id'],
		body: true,
		summary: 'Add a skill to a project',
	},
	{
		noun: 'projects',
		verb: 'remove-skill',
		fn: 'removeSkillFromProjectV1ProjectsProjectIdSkillsSkillIdDelete',
		method: 'DELETE',
		pathParams: ['project_id', 'skill_id'],
		body: false,
		summary: 'Remove a skill from a project',
	},
	{
		noun: 'projects',
		verb: 'upload-file',
		fn: 'uploadProjectFileV1ProjectsProjectIdFilesPost',
		method: 'POST',
		pathParams: ['project_id'],
		body: true,
		summary: 'Upload a file to a project',
	},
	{
		noun: 'projects',
		verb: 'list-files',
		fn: 'listProjectFilesV1ProjectsProjectIdFilesGet',
		method: 'GET',
		pathParams: ['project_id'],
		body: false,
		summary: 'List project files',
	},
	{
		noun: 'projects',
		verb: 'stream-file',
		fn: 'streamProjectFileV1ProjectsProjectIdFilesDownloadFilePathGet',
		method: 'GET',
		pathParams: ['project_id', 'file_path'],
		body: false,
		summary: 'Stream a project file',
	},
	{
		noun: 'projects',
		verb: 'download-file',
		fn: 'downloadProjectFileV1ProjectsProjectIdFilesFilePathGet',
		method: 'GET',
		pathParams: ['project_id', 'file_path'],
		body: false,
		summary: 'Download a project file',
	},
	{
		noun: 'projects',
		verb: 'delete-file',
		fn: 'deleteProjectFileV1ProjectsProjectIdFilesFilePathDelete',
		method: 'DELETE',
		pathParams: ['project_id', 'file_path'],
		body: false,
		summary: 'Delete a project file',
	},

	// skills
	{
		noun: 'skills',
		verb: 'list',
		fn: 'listSkillsV1SkillsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List skills',
	},
	{
		noun: 'skills',
		verb: 'create',
		fn: 'createSkillV1SkillsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a skill',
	},
	{
		noun: 'skills',
		verb: 'upload',
		fn: 'uploadSkillV1SkillsUploadPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Upload a skill',
	},
	{
		noun: 'skills',
		verb: 'get',
		fn: 'getSkillV1SkillsSkillIdGet',
		method: 'GET',
		pathParams: ['skill_id'],
		body: false,
		summary: 'Get a skill',
	},
	{
		noun: 'skills',
		verb: 'update',
		fn: 'updateSkillV1SkillsSkillIdPut',
		method: 'PUT',
		pathParams: ['skill_id'],
		body: true,
		summary: 'Update a skill',
	},
	{
		noun: 'skills',
		verb: 'delete',
		fn: 'deleteSkillV1SkillsSkillIdDelete',
		method: 'DELETE',
		pathParams: ['skill_id'],
		body: false,
		summary: 'Delete a skill',
	},
	{
		noun: 'skills',
		verb: 'install',
		fn: 'installSkillV1SkillsSkillIdInstallPost',
		method: 'POST',
		pathParams: ['skill_id'],
		body: false,
		summary: 'Install a skill from catalog',
	},
	{
		noun: 'skills',
		verb: 'content',
		fn: 'getSkillContentV1SkillsSkillIdContentGet',
		method: 'GET',
		pathParams: ['skill_id'],
		body: false,
		summary: 'Get skill content',
	},
	{
		noun: 'skills',
		verb: 'files',
		fn: 'listSkillFilesV1SkillsSkillIdFilesGet',
		method: 'GET',
		pathParams: ['skill_id'],
		body: false,
		summary: 'List skill files',
	},
	{
		noun: 'skills',
		verb: 'file-get',
		fn: 'getSkillFileV1SkillsSkillIdFilesPathGet',
		method: 'GET',
		pathParams: ['skill_id', 'path'],
		body: false,
		summary: 'Get a skill file',
	},
	{
		noun: 'skills',
		verb: 'member-add',
		fn: 'addSkillMemberV1SkillsSkillIdMembersPost',
		method: 'POST',
		pathParams: ['skill_id'],
		body: true,
		summary: 'Add a member skill',
	},
	{
		noun: 'skills',
		verb: 'members',
		fn: 'listSkillMembersV1SkillsSkillIdMembersGet',
		method: 'GET',
		pathParams: ['skill_id'],
		body: false,
		summary: 'List skill members',
	},
	{
		noun: 'skills',
		verb: 'member-remove',
		fn: 'removeSkillMemberV1SkillsSkillIdMembersChildSkillIdDelete',
		method: 'DELETE',
		pathParams: ['skill_id', 'child_skill_id'],
		body: false,
		summary: 'Remove a member skill',
	},
	{
		noun: 'skills',
		verb: 'flatten',
		fn: 'flattenSkillMembersV1SkillsSkillIdFlattenGet',
		method: 'GET',
		pathParams: ['skill_id'],
		body: false,
		summary: 'Flatten skill members',
	},
	{
		noun: 'skills',
		verb: 'collections-list',
		fn: 'listCollectionsV1SkillCollectionsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List skill collections',
	},
	{
		noun: 'skills',
		verb: 'collection-create',
		fn: 'createCollectionV1SkillCollectionsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a skill collection',
	},
	{
		noun: 'skills',
		verb: 'collection-get',
		fn: 'getCollectionV1SkillCollectionsCollectionIdGet',
		method: 'GET',
		pathParams: ['collection_id'],
		body: false,
		summary: 'Get a skill collection',
	},
	{
		noun: 'skills',
		verb: 'collection-update',
		fn: 'updateCollectionV1SkillCollectionsCollectionIdPut',
		method: 'PUT',
		pathParams: ['collection_id'],
		body: true,
		summary: 'Update a skill collection',
	},
	{
		noun: 'skills',
		verb: 'collection-delete',
		fn: 'deleteCollectionV1SkillCollectionsCollectionIdDelete',
		method: 'DELETE',
		pathParams: ['collection_id'],
		body: false,
		summary: 'Delete a skill collection',
	},
	{
		noun: 'skills',
		verb: 'collection-add-skill',
		fn: 'addSkillToCollectionV1SkillCollectionsCollectionIdSkillsPost',
		method: 'POST',
		pathParams: ['collection_id'],
		body: true,
		summary: 'Add a skill to a collection',
	},
	{
		noun: 'skills',
		verb: 'collection-remove-skill',
		fn: 'removeSkillFromCollectionV1SkillCollectionsCollectionIdSkillsSkillIdDelete',
		method: 'DELETE',
		pathParams: ['collection_id', 'skill_id'],
		body: false,
		summary: 'Remove a skill from a collection',
	},

	// clients
	{
		noun: 'clients',
		verb: 'list',
		fn: 'listClientsV1ClientsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List registered clients',
	},
	{
		noun: 'clients',
		verb: 'create',
		fn: 'createClientV1ClientsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a registered client',
	},
	{
		noun: 'clients',
		verb: 'get',
		fn: 'getClientV1ClientsClientIdGet',
		method: 'GET',
		pathParams: ['client_id'],
		body: false,
		summary: 'Get a registered client',
	},
	{
		noun: 'clients',
		verb: 'update',
		fn: 'updateClientV1ClientsClientIdPatch',
		method: 'PATCH',
		pathParams: ['client_id'],
		body: true,
		summary: 'Update a registered client',
	},
	{
		noun: 'clients',
		verb: 'delete',
		fn: 'deleteClientV1ClientsClientIdDelete',
		method: 'DELETE',
		pathParams: ['client_id'],
		body: false,
		summary: 'Delete a registered client',
	},
	{
		noun: 'clients',
		verb: 'add-skill',
		fn: 'addSkillToClientV1ClientsClientIdSkillsPost',
		method: 'POST',
		pathParams: ['client_id'],
		body: true,
		summary: 'Add a skill to a client',
	},
	{
		noun: 'clients',
		verb: 'remove-skill',
		fn: 'removeSkillFromClientV1ClientsClientIdSkillsSkillIdDelete',
		method: 'DELETE',
		pathParams: ['client_id', 'skill_id'],
		body: false,
		summary: 'Remove a skill from a client',
	},
	{
		noun: 'clients',
		verb: 'add-mcp',
		fn: 'addMcpInstanceToClientV1ClientsClientIdMcpInstancesPost',
		method: 'POST',
		pathParams: ['client_id'],
		body: true,
		summary: 'Add an MCP instance to a client',
	},
	{
		noun: 'clients',
		verb: 'remove-mcp',
		fn: 'removeMcpInstanceFromClientV1ClientsClientIdMcpInstancesMcpInstanceIdDelete',
		method: 'DELETE',
		pathParams: ['client_id', 'mcp_instance_id'],
		body: false,
		summary: 'Remove an MCP instance from a client',
	},
	{
		noun: 'clients',
		verb: 'pull-from-project',
		fn: 'pullFromProjectV1ClientsClientIdPullFromProjectPost',
		method: 'POST',
		pathParams: ['client_id'],
		body: true,
		summary: 'Pull skills/MCPs from a project into a client',
	},

	// apikeys
	{
		noun: 'apikeys',
		verb: 'list',
		fn: 'listApiKeysV1ApiKeysGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List API keys',
	},
	{
		noun: 'apikeys',
		verb: 'create',
		fn: 'createApiKeyV1ApiKeysPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an API key',
	},
	{
		noun: 'apikeys',
		verb: 'get',
		fn: 'getApiKeyV1ApiKeysTokenIdGet',
		method: 'GET',
		pathParams: ['token_id'],
		body: false,
		summary: 'Get an API key',
	},
	{
		noun: 'apikeys',
		verb: 'revoke',
		fn: 'revokeApiKeyV1ApiKeysTokenIdDelete',
		method: 'DELETE',
		pathParams: ['token_id'],
		body: false,
		summary: 'Revoke an API key',
	},

	// bundles
	{
		noun: 'bundles',
		verb: 'analyze',
		fn: 'analyzeBundleV1BundlesAnalyzePost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Analyze a bundle',
	},
	{
		noun: 'bundles',
		verb: 'install',
		fn: 'installBundleV1BundlesInstallPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Install a bundle',
	},

	// registries
	{
		noun: 'registries',
		verb: 'list',
		fn: 'listRegistriesV1RegistriesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List registries',
	},
	{
		noun: 'registries',
		verb: 'create',
		fn: 'createRegistryV1RegistriesPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create a registry',
	},
	{
		noun: 'registries',
		verb: 'get',
		fn: 'getRegistryV1RegistriesRegistryIdGet',
		method: 'GET',
		pathParams: ['registry_id'],
		body: false,
		summary: 'Get a registry',
	},
	{
		noun: 'registries',
		verb: 'update',
		fn: 'updateRegistryV1RegistriesRegistryIdPatch',
		method: 'PATCH',
		pathParams: ['registry_id'],
		body: true,
		summary: 'Update a registry',
	},
	{
		noun: 'registries',
		verb: 'delete',
		fn: 'deleteRegistryV1RegistriesRegistryIdDelete',
		method: 'DELETE',
		pathParams: ['registry_id'],
		body: false,
		summary: 'Delete a registry',
	},
	{
		noun: 'registries',
		verb: 'sync',
		fn: 'syncRegistryV1RegistriesRegistryIdSyncPost',
		method: 'POST',
		pathParams: ['registry_id'],
		body: false,
		summary: 'Sync a registry',
	},
	{
		noun: 'registries',
		verb: 'items',
		fn: 'listRegistryItemsV1RegistriesRegistryIdItemsGet',
		method: 'GET',
		pathParams: ['registry_id'],
		body: false,
		summary: 'List registry items',
	},
	{
		noun: 'registries',
		verb: 'update-all',
		fn: 'updateAllSpecsV1RegistriesRegistryIdUpdateAllPost',
		method: 'POST',
		pathParams: ['registry_id'],
		body: false,
		summary: 'Update all specs in a registry',
	},

	// catalog
	{
		noun: 'catalog',
		verb: 'search',
		fn: 'searchCatalogV1RegistriesCatalogSearchGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Search the catalog',
	},
	{
		noun: 'catalog',
		verb: 'get-item',
		fn: 'getCatalogItemV1RegistriesCatalogItemsItemIdGet',
		method: 'GET',
		pathParams: ['item_id'],
		body: false,
		summary: 'Get a catalog item',
	},
	{
		noun: 'catalog',
		verb: 'update-item',
		fn: 'updateItemSpecV1RegistriesCatalogItemsItemIdUpdatePost',
		method: 'POST',
		pathParams: ['item_id'],
		body: false,
		summary: 'Update a catalog item spec',
	},

	// connections (OpenAPI)
	{
		noun: 'connections',
		verb: 'list',
		fn: 'listConnectionsV1OpenapiConnectionsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List OpenAPI connections',
	},
	{
		noun: 'connections',
		verb: 'create',
		fn: 'createConnectionV1OpenapiConnectionsPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Create an OpenAPI connection',
	},
	{
		noun: 'connections',
		verb: 'preview-spec',
		fn: 'previewSpecV1OpenapiConnectionsPreviewSpecPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Preview an OpenAPI spec before creating a connection',
	},
	{
		noun: 'connections',
		verb: 'get',
		fn: 'getConnectionV1OpenapiConnectionsConnectionIdGet',
		method: 'GET',
		pathParams: ['connection_id'],
		body: false,
		summary: 'Get an OpenAPI connection',
	},
	{
		noun: 'connections',
		verb: 'update',
		fn: 'updateConnectionV1OpenapiConnectionsConnectionIdPatch',
		method: 'PATCH',
		pathParams: ['connection_id'],
		body: true,
		summary: 'Update an OpenAPI connection',
	},
	{
		noun: 'connections',
		verb: 'delete',
		fn: 'deleteConnectionV1OpenapiConnectionsConnectionIdDelete',
		method: 'DELETE',
		pathParams: ['connection_id'],
		body: false,
		summary: 'Delete an OpenAPI connection',
	},
	{
		noun: 'connections',
		verb: 'discover-tools',
		fn: 'discoverToolsV1OpenapiConnectionsConnectionIdDiscoverToolsPost',
		method: 'POST',
		pathParams: ['connection_id'],
		body: false,
		summary: 'Discover tools from an OpenAPI connection',
	},

	// audit-logs
	{
		noun: 'audit-logs',
		verb: 'list',
		fn: 'listAuditLogsV1AuditLogsGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List audit logs',
	},

	// inbox
	{
		noun: 'inbox',
		verb: 'list',
		fn: 'getInboxItemsV1InboxGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List inbox items',
	},

	// files (workspace-level)
	{
		noun: 'files',
		verb: 'list',
		fn: 'listWorkspaceFilesV1FilesGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'List workspace files',
	},
	{
		noun: 'files',
		verb: 'upload',
		fn: 'uploadWorkspaceFileV1FilesPost',
		method: 'POST',
		pathParams: [],
		body: true,
		summary: 'Upload a workspace file',
	},
	{
		noun: 'files',
		verb: 'history',
		fn: 'workspaceFileHistoryV1FilesHistoryGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get workspace file history',
	},
	{
		noun: 'files',
		verb: 'stream',
		fn: 'streamWorkspaceFileV1FilesDownloadFilePathGet',
		method: 'GET',
		pathParams: ['file_path'],
		body: false,
		summary: 'Stream a workspace file',
	},
	{
		noun: 'files',
		verb: 'download',
		fn: 'downloadWorkspaceFileV1FilesFilePathGet',
		method: 'GET',
		pathParams: ['file_path'],
		body: false,
		summary: 'Download a workspace file',
	},

	// network
	{
		noun: 'network',
		verb: 'topology',
		fn: 'getNetworkTopologyV1NetworkTopologyGet',
		method: 'GET',
		pathParams: [],
		body: false,
		summary: 'Get agent network topology',
	},

	// webhooks (receiver endpoints at /webhooks/{webhook_id})
	{
		noun: 'webhooks',
		verb: 'get',
		fn: 'handleWebhookWebhooksWebhookIdPatch',
		method: 'GET',
		pathParams: ['webhook_id'],
		body: false,
		summary: 'Get a webhook handler',
	},
	{
		noun: 'webhooks',
		verb: 'handle',
		fn: 'handleWebhookWebhooksWebhookIdPatch',
		method: 'POST',
		pathParams: ['webhook_id'],
		body: false,
		summary: 'Handle an incoming webhook',
	},
	{
		noun: 'webhooks',
		verb: 'delete',
		fn: 'handleWebhookWebhooksWebhookIdPatch',
		method: 'DELETE',
		pathParams: ['webhook_id'],
		body: false,
		summary: 'Delete a webhook handler',
	},
];
