version: '3.8'

# Development overrides for hot reload and debugging
services:
  api:
    build:
      target: builder  # Use builder stage for development to have all dev dependencies
    command: ["uvicorn", "agentarea_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount entire source code for hot reload
      - ./apps/api:/app/apps/api
      - ./libs:/app/libs
      - ./.secrets.json:/app/.secrets.json:ro
      - ./apps/api/alembic:/app/apps/api/alembic
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugging

  worker:
    build:
      target: builder  # Use builder stage for development
    environment:
      - ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount entire source code for hot reload
      - ./apps/worker:/app/apps/worker
      - ./libs:/app/libs
      - ./.secrets.json:/app/.secrets.json:ro

  # Enable development tools by default
  redis-commander:
    profiles: []  # Remove profile to start by default in dev

  pgadmin:
    profiles: []  # Remove profile to start by default in dev 