FROM golang:1.25-alpine

RUN apk add --no-cache git ca-certificates dumb-init && rm -rf /var/cache/apk/*
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["air", "-c", ".air.toml"]
