FROM golang:1.26-alpine

RUN apk add --no-cache git ca-certificates dumb-init && rm -rf /var/cache/apk/*
RUN go install github.com/air-verse/air@v1.67.4

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["air", "-c", ".air.toml"]
