run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - goconst
    - gocyclo
    - funlen
    - nestif
    - prealloc
    - exportloopref
    - revive
    - misspell
    - errcheck
    - unconvert
    - unparam
  disable:
    - typecheck # Disable typecheck due to import resolution issues in CI

linters-settings:
  errcheck:
    exclude-functions:
      - (*log.Logger).Print*
      - (*log.Logger).Printf
      - (*log.Logger).Println
    # Remove the deprecated ignore option
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false