#!/bin/sh
# Generates the local development credentials that docker-compose.yaml and
# docker-compose.dev.yaml require. Nothing here ships in the repository: every
# value is unique to your machine, which is why the compose files fail hard when
# they are missing.
#
# Usage:  ./scripts/gen-dev-secrets.sh [--force]
#
# Without --force the script tops up only the keys that are missing or empty and
# leaves existing values alone, so running it after a compose upgrade cannot
# silently rotate the secrets your running stack already depends on.
set -eu

fail() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
# shellcheck source=lib/secrets.sh
. "$repo_root/scripts/lib/secrets.sh"

env_file="$repo_root/.env"
jwks_file="$repo_root/config/auth/kratos/jwks.json"
force=0
[ "${1:-}" = "--force" ] && force=1

# Every key this script owns, listed once. The guard, the rewrite filter and the
# generated block all derive from this list, so they cannot drift apart the way
# a hardcoded probe key does.
managed_keys='KRATOS_JWKS_B64
KRATOS_SECRETS_COOKIE
KRATOS_SECRETS_CIPHER
HYDRA_SECRETS_SYSTEM
HYDRA_SECRETS_COOKIE
HYDRA_PAIRWISE_SALT
SANDBOX_ACTIVATION_AUTH_SECRET
SANDBOX_CLEANUP_AUTH_SECRET'

# A key counts as set only when it has a non-empty value. Compose declares these
# as ${VAR:?}, which rejects an empty assignment exactly like a missing one, so
# `KEY=` in .env must not read as "already configured".
is_set() {
  [ -f "$env_file" ] && grep -qE "^$1=." "$env_file"
}

pending=''
for key in $managed_keys; do
  if [ "$force" -eq 1 ] || ! is_set "$key"; then
    pending="$pending$key
"
  fi
done

if [ -z "$pending" ]; then
  printf 'Development secrets already present in %s\n' "$env_file"
  printf 'Re-run with --force to replace them (this invalidates existing sessions).\n'
  exit 0
fi

if [ -f "$env_file" ]; then
  cp "$env_file" "$env_file.bak"
  printf 'Backed up existing env to %s.bak\n' "$env_file"
  # Drop only the keys about to be written, so the appended block is
  # authoritative for those and every other value survives untouched.
  filter=$(printf '%s' "$pending" | tr '\n' '|' | sed 's/|$//')
  tmp_env="$env_file.tmp"
  grep -v -E "^($filter)=" "$env_file" > "$tmp_env" || true
  mv "$tmp_env" "$env_file"
fi

value_for() {
  case "$1" in
    # Writes the private half to $jwks_file and prints the public half.
    KRATOS_JWKS_B64) generate_jwks "$jwks_file" ;;
    # HMAC keys, not Ory cipher secrets: no 32-character constraint.
    SANDBOX_ACTIVATION_AUTH_SECRET|SANDBOX_CLEANUP_AUTH_SECRET) random_token 32 ;;
    *) random_secret_32 ;;
  esac
}

{
  printf '\n# --- generated by scripts/gen-dev-secrets.sh; do not commit ---\n'
  for key in $pending; do
    if [ "$key" = KRATOS_JWKS_B64 ]; then
      printf '# Public half only. Kratos signs with the private half in\n'
      printf '# config/auth/kratos/jwks.json, which is gitignored.\n'
    fi
    printf '%s=%s\n' "$key" "$(value_for "$key")"
  done
} >> "$env_file"

chmod 600 "$env_file"

printf 'Wrote development secrets to %s:\n' "$env_file"
for key in $pending; do
  printf '  %s\n' "$key"
done
if printf '%s' "$pending" | grep -q '^KRATOS_JWKS_B64$'; then
  printf 'Wrote Kratos signing key to %s (mode 600, gitignored)\n' "$jwks_file"
fi
