#!/bin/sh
# Generates the local development credentials that docker-compose.dev.yaml
# requires. Nothing here ships in the repository: every value is unique to your
# machine, which is why the compose files fail hard when they are missing.
#
# Usage:  ./scripts/gen-dev-secrets.sh [--force]
set -eu

fail() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
# shellcheck source=lib/secrets.sh
. "$repo_root/scripts/lib/secrets.sh"

env_file="$repo_root/.env"
jwks_file="$repo_root/config/auth/kratos/jwks.json"
force=0
[ "${1:-}" = "--force" ] && force=1

already_set() {
  [ -f "$env_file" ] && grep -q "^$1=" "$env_file"
}

if [ "$force" -eq 0 ] && already_set KRATOS_JWKS_B64; then
  printf 'Development secrets already present in %s\n' "$env_file"
  printf 'Re-run with --force to replace them (this invalidates existing sessions).\n'
  exit 0
fi

if [ "$force" -eq 1 ] && [ -f "$env_file" ]; then
  cp "$env_file" "$env_file.bak"
  printf 'Backed up existing env to %s.bak\n' "$env_file"
  # Drop the managed keys so the appended block is authoritative.
  tmp_env="$env_file.tmp"
  grep -v -E '^(KRATOS_JWKS_B64|KRATOS_SECRETS_COOKIE|KRATOS_SECRETS_CIPHER|HYDRA_SECRETS_SYSTEM|HYDRA_SECRETS_COOKIE|HYDRA_PAIRWISE_SALT)=' \
    "$env_file" > "$tmp_env" || true
  mv "$tmp_env" "$env_file"
fi

jwks_public_b64=$(generate_jwks "$jwks_file")

cat >> "$env_file" <<EOF

# --- generated by scripts/gen-dev-secrets.sh; do not commit ---
# Public half only. Kratos signs with the private half in
# config/auth/kratos/jwks.json, which is gitignored.
KRATOS_JWKS_B64=$jwks_public_b64
KRATOS_SECRETS_COOKIE=$(random_secret_32)
KRATOS_SECRETS_CIPHER=$(random_secret_32)
HYDRA_SECRETS_SYSTEM=$(random_secret_32)
HYDRA_SECRETS_COOKIE=$(random_secret_32)
HYDRA_PAIRWISE_SALT=$(random_secret_32)
EOF

chmod 600 "$env_file"

printf 'Wrote development secrets to %s\n' "$env_file"
printf 'Wrote Kratos signing key to %s (mode 600, gitignored)\n' "$jwks_file"
