http:
    routers:
        mcp-manager-api:
            rule: PathPrefix(`/api/mcp`)
            service: mcp-manager-service
            entryPoints:
                - web
            middlewares:
                - mcp-api-stripprefix
        mcp-manager-catchall:
            rule: '!PathPrefix(`/mcp/`) && !PathPrefix(`/api/mcp`)'
            service: mcp-manager-service
            entryPoints:
                - web
        mcp-manager-health:
            rule: Path(`/health`)
            service: mcp-manager-service
            entryPoints:
                - web
        mcp-nginx-704e5037:
            rule: PathPrefix(`/mcp/nginx-704e5037`)
            service: mcp-nginx-704e5037-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-704e5037-stripprefix
        mcp-nginx-e68fb249:
            rule: PathPrefix(`/mcp/nginx-e68fb249`)
            service: mcp-nginx-e68fb249-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-e68fb249-stripprefix
        mcp-nginx-test-server-instance-fac991fe:
            rule: PathPrefix(`/mcp/nginx-test-server-instance-fac991fe`)
            service: mcp-nginx-test-server-instance-fac991fe-service
            entryPoints:
                - web
            middlewares:
                - mcp-nginx-test-server-instance-fac991fe-stripprefix
        mcp-test-nginx-server-cb3bd69f:
            rule: PathPrefix(`/mcp/test-nginx-server-cb3bd69f`)
            service: mcp-test-nginx-server-cb3bd69f-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-nginx-server-cb3bd69f-stripprefix
    services:
        mcp-manager-service:
            loadBalancer:
                servers:
                    - url: http://mcp-manager:8000
        mcp-nginx-704e5037-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-nginx-e68fb249-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-nginx-test-server-instance-fac991fe-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:8000
        mcp-test-nginx-server-cb3bd69f-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:80
    middlewares:
        mcp-api-stripprefix:
            stripPrefix:
                prefixes:
                    - /api/mcp
                forceSlash: false
        mcp-nginx-704e5037-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-704e5037
                forceSlash: false
        mcp-nginx-e68fb249-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-e68fb249
                forceSlash: false
        mcp-nginx-test-server-instance-fac991fe-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/nginx-test-server-instance-fac991fe
                forceSlash: false
        mcp-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp
                forceSlash: false
        mcp-test-nginx-server-cb3bd69f-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-nginx-server-cb3bd69f
                forceSlash: false
