http:
    routers:
        mcp-manager-api:
            rule: PathPrefix(`/api/mcp`)
            service: mcp-manager-service
            entryPoints:
                - web
            middlewares:
                - mcp-api-stripprefix
        mcp-manager-catchall:
            rule: '!PathPrefix(`/mcp/`) && !PathPrefix(`/api/mcp`)'
            service: mcp-manager-service
            entryPoints:
                - web
        mcp-manager-health:
            rule: Path(`/health`)
            service: mcp-manager-service
            entryPoints:
                - web
        mcp-test-instance-d4fda19d:
            rule: PathPrefix(`/mcp/test-instance-d4fda19d`)
            service: mcp-test-instance-d4fda19d-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-instance-d4fda19d-stripprefix
        mcp-test-mcp-instance-f2665b00:
            rule: PathPrefix(`/mcp/test-mcp-instance-f2665b00`)
            service: mcp-test-mcp-instance-f2665b00-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-mcp-instance-f2665b00-stripprefix
        mcp-test-redis-event-633828f7:
            rule: PathPrefix(`/mcp/test-redis-event-633828f7`)
            service: mcp-test-redis-event-633828f7-service
            entryPoints:
                - web
            middlewares:
                - mcp-test-redis-event-633828f7-stripprefix
    services:
        mcp-manager-service:
            loadBalancer:
                servers:
                    - url: http://localhost:8000
        mcp-test-instance-d4fda19d-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.3:80
        mcp-test-mcp-instance-f2665b00-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.2:80
        mcp-test-redis-event-633828f7-service:
            loadBalancer:
                servers:
                    - url: http://10.88.0.4:80
    middlewares:
        mcp-api-stripprefix:
            stripPrefix:
                prefixes:
                    - /api/mcp
                forceSlash: false
        mcp-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp
                forceSlash: false
        mcp-test-instance-d4fda19d-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-instance-d4fda19d
                forceSlash: false
        mcp-test-mcp-instance-f2665b00-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-mcp-instance-f2665b00
                forceSlash: false
        mcp-test-redis-event-633828f7-stripprefix:
            stripPrefix:
                prefixes:
                    - /mcp/test-redis-event-633828f7
                forceSlash: false
