{{- if not .Values.dataPlane.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataplane.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dataplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.dataPlane.auth.token | quote }}
{{- end }}
