name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      component:
        description: 'Component name (e.g., api, worker, frontend)'
        required: true
        type: string
      context:
        description: 'Build context directory'
        required: true
        type: string
      dockerfile:
        description: 'Path to Dockerfile'
        required: true
        type: string
      image-name:
        description: 'Docker image name (defaults to agentarea-{component})'
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      DOCKER_REGISTRY_MIRROR:
        required: false
      DOCKER_REGISTRY_MIRROR_USERNAME:
        required: false
      DOCKER_REGISTRY_MIRROR_PASSWORD:
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to Private Registry
        if: ${{ secrets.DOCKER_REGISTRY_MIRROR != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_MIRROR }}
          username: ${{ secrets.DOCKER_REGISTRY_MIRROR_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_MIRROR_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            agentarea/${{ inputs.image-name || format('agentarea-{0}', inputs.component) }}
            ${{ secrets.DOCKER_REGISTRY_MIRROR }}/agentarea/${{ inputs.image-name || format('agentarea-{0}', inputs.component) }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=dev,enable={{is_default_branch}}
            type=sha,format=short,prefix=commit-
            type=sha,prefix={{branch}}-
          flavor: |
            latest=auto

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ inputs.component }}
          cache-to: type=gha,mode=max,scope=${{ inputs.component }}
          provenance: false

      - name: Image digest
        run: echo "Built and pushed ${{ inputs.component }} image with digest ${{ steps.meta.outputs.digest }}"
