name: Frontend CI workflow
on:
  push:
    paths:
      - "frontend/**"
      - ".github/**"
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/**"

env:
  CONTAINER_NAME: agentarea-frontend

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Cache deps
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"
          node-version: 20.x

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Build application
        run: pnpm run build

      # - run: zip -qq -r build.zip dist

      # # Share artifact inside workflow
      # - name: Share artifact inside workflow
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: ./frontend/build.zip
      #     name: build.zip
