name: MCP Infra CI

on:
  push:
    branches: [main, develop, master]
    paths:
      - 'mcp-infrastructure/**'
      - '.github/workflows/mcp-infra.yaml'
  pull_request:
    branches: [main, develop, master]
    paths:
      - 'mcp-infrastructure/**'
      - '.github/workflows/mcp-infra.yaml'

concurrency:
  group: mcp-infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (golangci-lint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcp-infrastructure/go-mcp-manager
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.58.2
          working-directory: mcp-infrastructure/go-mcp-manager
          args: --timeout=5m

      - name: Go vet
        run: go vet ./...

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: mcp-infrastructure/go-mcp-manager
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: |
          go test ./... -race -coverprofile=coverage.out -v | tee test-report.txt

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mcp-infra-test-artifacts
          path: |
            mcp-infrastructure/go-mcp-manager/coverage.out
            mcp-infrastructure/go-mcp-manager/test-report.txt