"""Image and video generation for one task, with its video jobs persisted."""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from uuid import UUID

from agentarea_common.extensions.customer_pricing import CustomerPricing
from agentarea_common.money import Money

from agentarea_llm.application.model_call_pricing import price_model_call
from agentarea_llm.application.model_service import ModelService
from agentarea_llm.domain.media import VideoJobStatus
from agentarea_llm.infrastructure.model_clients import (
    GeneratedMedia,
    ModelCallError,
    ModelCostUnavailableError,
)
from agentarea_llm.infrastructure.video_generation_job_repository import (
    VideoGenerationJobRepository,
)


class MediaModelNotConfiguredError(ValueError):
    """The toolset was asked for a medium its settings name no model for."""


class VideoJobNotFoundError(LookupError):
    """No video job with this id was submitted by this task."""


@dataclass(frozen=True)
class BilledMedia:
    """Generated bytes and what they cost the customer, in ``currency``."""

    content: bytes
    media_type: str
    cost: Money
    currency: str


@dataclass(frozen=True)
class SubmittedJob:
    """Our id for a submitted video generation; the provider's stays in the row."""

    job_id: str
    status: VideoJobStatus


@dataclass(frozen=True)
class VideoCheck:
    """Where a video job stands.

    ``video``, ``cost_usd`` (the provider's charge) and ``cost`` (the customer's,
    in ``currency``) are set when it finished and has not been saved yet;
    ``file_path`` when an earlier check already saved (and billed) it.
    """

    job_id: str
    status: VideoJobStatus
    error: str | None = None
    video: GeneratedMedia | None = None
    cost_usd: Decimal | None = None
    cost: Money | None = None
    currency: str | None = None
    file_path: str | None = None


class MediaGenerationService:
    def __init__(
        self,
        *,
        models: ModelService,
        jobs: VideoGenerationJobRepository,
        task_id: str | None,
        image_model_id: str | None,
        video_model_id: str | None,
        call_ref: str,
        pricing: CustomerPricing | None = None,
    ) -> None:
        # The tool call this service acts for, the same on every retry of it; a
        # finished video is billed to exactly one call.
        self._call_ref = call_ref
        # None = the process-wide pricing, resolved per call (see get_customer_pricing).
        self._pricing = pricing
        self._models = models
        self._jobs = jobs
        self._task_id = task_id
        self._image_model_id = image_model_id
        self._video_model_id = video_model_id

    async def generate_image(self, prompt: str, *, size: str | None = None) -> BilledMedia:
        if not self._image_model_id:
            raise MediaModelNotConfiguredError("no image model is configured for agentarea/media")
        model = await self._models.image_model(self._image_model_id)
        image = await model.generate(prompt, size=size)
        if image.cost_usd is None:
            raise ModelCostUnavailableError("the image model reported no cost")
        priced = await price_model_call(
            model.endpoint, provider_cost_usd=image.cost_usd, pricing=self._pricing
        )
        return BilledMedia(
            content=image.content,
            media_type=image.media_type,
            cost=priced.amount,
            currency=priced.currency,
        )

    async def submit_video(
        self,
        prompt: str,
        *,
        duration: int | None = None,
        resolution: str | None = None,
        aspect_ratio: str | None = None,
    ) -> SubmittedJob:
        if not self._video_model_id:
            raise MediaModelNotConfiguredError("no video model is configured for agentarea/media")
        model = await self._models.video_model(self._video_model_id)
        submitted = await model.submit(
            prompt, duration=duration, resolution=resolution, aspect_ratio=aspect_ratio
        )
        job = await self._jobs.create(
            model_instance_id=UUID(self._video_model_id),
            task_id=self._task_id,
            provider_job_id=submitted.provider_job_id,
            prompt=prompt,
            status=submitted.status,
        )
        return SubmittedJob(job_id=str(job.id), status=submitted.status)

    async def check_video(self, job_id: str) -> VideoCheck:
        try:
            job_uuid = UUID(job_id)
        except ValueError as error:
            raise VideoJobNotFoundError(f"video job {job_id!r} is not a job id") from error
        job = await self._jobs.get_for_task(job_uuid, self._task_id)
        if job is None:
            raise VideoJobNotFoundError(f"no video job {job_id} was submitted by this task")
        if job.file_path:
            # A retry of the call that billed it reports the charge again; the
            # workflow keeps one result per call, so it is still counted once.
            billed_here = job.billed_call_ref == self._call_ref
            return VideoCheck(
                job_id=job_id,
                status=VideoJobStatus.COMPLETED,
                file_path=job.file_path,
                cost=job.billed_cost if billed_here else None,
            )
        stored = VideoJobStatus(job.status)
        if stored.is_failed:
            return VideoCheck(job_id=job_id, status=stored, error=job.error)

        model = await self._models.video_model(job.model_instance_id)
        status = await model.status(job.provider_job_id)
        if status.status.is_running:
            if status.status != stored:
                await self._jobs.update(job.id, status=status.status)
            return VideoCheck(job_id=job_id, status=status.status)
        if status.status.is_failed:
            error = status.error or f"the provider reports the job {status.status}"
            await self._jobs.update(job.id, status=status.status, error=error)
            return VideoCheck(job_id=job_id, status=status.status, error=error)
        if status.status is not VideoJobStatus.COMPLETED:
            raise ModelCallError(f"video job {job_id} has unhandled status {status.status!r}")
        if status.cost_usd is None:
            raise ModelCostUnavailableError(
                f"video job {job_id} finished without a reported cost, so it cannot be billed"
            )
        video = await model.content(job.provider_job_id)
        priced = await price_model_call(
            model.endpoint, provider_cost_usd=status.cost_usd, pricing=self._pricing
        )
        return VideoCheck(
            job_id=job_id,
            status=VideoJobStatus.COMPLETED,
            video=video,
            cost_usd=status.cost_usd,
            cost=priced.amount,
            currency=priced.currency,
        )

    async def record_video_saved(
        self, job_id: str, file_path: str, cost_usd: Decimal, cost: Money
    ) -> bool:
        """Mark the job saved; True when this call is the one that bills it."""
        return await self._jobs.record_saved(
            UUID(job_id),
            file_path,
            cost_usd=cost_usd,
            billed_cost=cost,
            call_ref=self._call_ref,
        )
